/**
 * src/pages/QAPanel/mappedItemsData.js
 * 
 * Itens técnicos de conformidade, arquitetura e blindagens de segurança mapeados pelas 5 Squads.
 */

export const MAPPED_TECHNICAL_ITEMS = [
  // ==========================================
  // SQUAD 1: CYBER SECURITY & APPSEC
  // ==========================================
  {
    id: "SEC-MAP-001",
    technicalName: "activeSessionMiddleware.ts - Token Revocation Cutoff Enforcement",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Middleware interceptador em Express validando carimbo de corte temporal (iat <= revokedAt) e rejeitando tokens emitidos antes do logout global.",
    affectedFile: "src/middleware/activeSessionMiddleware.ts",
    compliance: "OWASP ASVS v4.0 V2.1.8 / RFC 7009",
    details: "Verificação síncrona com fallback para GoTrue. Rejeição imediata com HTTP 401 TOKEN_REVOKED.",
  },
  {
    id: "SEC-MAP-002",
    technicalName: "jwtLifecycleManager.ts - Access Token Max TTL <= 900s Policy",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 4h",
    description: "Validador estrito de tempo de vida de Access Token rejeitando qualquer JWT com exp - iat > 900 segundos (15 minutos).",
    affectedFile: "src/security/jwtLifecycleManager.ts",
    compliance: "NIST SP 800-63B Section 7.1 / OWASP Top 10 A07",
    details: "Impede o uso de tokens de longa duração. Força rotação e uso de Refresh Tokens efêmeros.",
  },
  {
    id: "SEC-MAP-003",
    technicalName: "jwtLifecycleManager.ts - Blocked Users Compulsory Eviction Registry",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 1h",
    description: "Registro em memória de usuários bloqueados administrativamente com expurgo instantâneo de requisições subsequentes (HTTP 401 USER_BLOCKED).",
    affectedFile: "src/security/jwtLifecycleManager.ts",
    compliance: "OWASP ASVS V2.1.9",
    details: "Bloqueio em tempo real sem dependência exclusiva de expiração de token.",
  },
  {
    id: "SEC-MAP-004",
    technicalName: "tenantIsolationValidator.js - Client-Controlled Tenant ID Injection Defense (Anti-BOLA)",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Validador impedindo que requisições de clientes sobrescrevam ou injetem tenant_id arbitrário no payload ou query parameters.",
    affectedFile: "src/security/tenantIsolationValidator.js",
    compliance: "OWASP API Security Top 10 (API1:2023 - BOLA)",
    details: "Garante ancoragem estrita do tenant_id na claim JWT validada pelo backend.",
  },
  {
    id: "SEC-MAP-005",
    technicalName: "Supabase Auth Dashboard - Configure JWT Expiry to 900s & Enable Refresh Token Rotation",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 24h",
    description: "Configuração do painel de administração do Supabase para limitar tempo de expiração do JWT em 900s e ativar rotação de Refresh Token.",
    affectedFile: "Painel Supabase (Authentication -> Settings)",
    compliance: "OWASP ASVS V2.1.8 / RFC 6749",
    details: "Acessar https://supabase.com/dashboard/project/<PROJETO>/settings/auth e ajustar JWT Expiry = 900s e Refresh Token Reuse Interval = 10s.",
  },

  // ==========================================
  // SQUAD 2: FRONT-END & UI/UX
  // ==========================================
  {
    id: "FE-MAP-001",
    technicalName: "SafeHtml.jsx - DOMPurify Strict Sanitizer Component",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 4h",
    description: "Componente React para renderização de textos e descrições com purificação estrita contra XSS, neutralizando <script>, <iframe> e inline handlers.",
    affectedFile: "src/components/ui/SafeHtml.jsx",
    compliance: "OWASP Top 10 A03:2021 (Injection) / CWE-79",
    details: "Configurado com FORBID_TAGS e FORBID_ATTR, além de forçar rel='noopener noreferrer' e target='_blank' em links.",
  },
  {
    id: "FE-MAP-002",
    technicalName: "TurnstileWidget.jsx - Cloudflare Turnstile Interactive Challenge",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 6h",
    description: "Widget interativo de desafio CAPTCHA invisível/gerenciado para proteção contra ataques automatizados de força bruta e credential stuffing.",
    affectedFile: "src/components/security/TurnstileWidget.jsx",
    compliance: "OWASP Automated Threat Handbook (OAT-007)",
    details: "Integração client-side com token emitido e validado obrigatoriamente no login.",
  },
  {
    id: "FE-MAP-003",
    technicalName: "Cloudflare Turnstile Dashboard - Register Domain & Site Key",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "HIGH (P1)",
    sla: "SLA: 24h",
    description: "Cadastro do domínio oficial da aplicação no painel Cloudflare para emissão das credenciais de produção do Turnstile (Site Key pública).",
    affectedFile: "Painel Cloudflare (dash.cloudflare.com)",
    compliance: "Bot Management / Anti-Automation",
    details: "Registrar domínio barbeariasaas.com.br e copiar VITE_TURNSTILE_SITE_KEY para o arquivo .env de produção.",
  },
  {
    id: "FE-MAP-004",
    technicalName: "masks.js - Defensive Masking & Sensitive Data Blur Utilities",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "MEDIUM (P2)",
    sla: "SLA: 12h",
    description: "Utilitários de máscara em tempo real para campos de CPF, telefone e moeda, impedindo a visualização indiscriminada de identificadores.",
    affectedFile: "src/utils/masks.js",
    compliance: "LGPD Art. 46 / OWASP Privacy Risks",
    details: "Aplica máscaras em inputs e formata saídas visuais sem armazenar caracteres especiais desnecessários.",
  },
  {
    id: "FE-MAP-008",
    technicalName: "SkeletonCard.jsx & SkeletonBookingView.jsx - High Latency UX Resilience",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 8h",
    description: "Componentes de Skeleton Screen com transições suaves para feedback instantâneo de carregamento em requisições de alta latência (>1200ms).",
    affectedFile: "src/components/resilience/SkeletonCard.jsx",
    compliance: "Google Web Vitals (CLS = 0) / Nielsen Norman Group Feedback Heuristic",
    details: "Variantes para serviços, profissionais, horários e dashboards, prevenindo saltos visuais de layout.",
  },
  {
    id: "FE-MAP-005",
    technicalName: "OfflineBanner.jsx & useNetworkResilience.js - Realtime WebSocket & Offline Indicator",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 4h",
    description: "Indicador discreto de estado de conexão acionado automaticamente na perda de rede ou desconexão do canal WebSocket Supabase Realtime.",
    affectedFile: "src/components/resilience/OfflineBanner.jsx",
    compliance: "RFC 6455 WebSocket / W3C Network Information API",
    details: "Exibe status 'Modo Offline / Reconectando...' com botão de reconexão manual e simulação de instabilidade.",
  },
  {
    id: "FE-MAP-006",
    technicalName: "ResilientFormHandler.jsx - Friendly Error Recovery & Input Retention",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Tratamento amigável para falhas de requisição de agendamento retendo 100% dos dados preenchidos com botão 'Tentar Novamente'.",
    affectedFile: "src/components/resilience/ResilientFormHandler.jsx",
    compliance: "OWASP Resilient Client Design / WCAG 2.1 Error Prevention",
    details: "Buffer em memória e sessionStorage; sumário dos dados salvos e ação de reenvio sem recarregamento.",
  },

  // ==========================================
  // SQUAD 3: BACK-END & CORE APIS
  // ==========================================
  {
    id: "BE-MAP-001",
    technicalName: "appointmentsSecureQuery.ts - Supabase Parameterized Query Builder",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Eliminação completa de SQL manual concatenado; uso exclusivo do construtor de consultas do Supabase JS com parameter binding nativo.",
    affectedFile: "src/api/appointmentsSecureQuery.ts",
    compliance: "OWASP Top 10 A03:2021 / CWE-89 (SQLi)",
    details: "Imuniza buscas de clientes com apóstrofos e aspas (caso D'Angelo) e previne Blind SQLi.",
  },
  {
    id: "BE-MAP-002",
    technicalName: "supabaseAdminRevocation.ts - GoTrue Global SignOut & Sessions Invalidation API",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Módulo de API administrativa para acionar revogação em massa de Refresh Tokens e inativação de sessões na base relacional.",
    affectedFile: "src/api/supabaseAdminRevocation.ts",
    compliance: "RFC 7009 / OWASP ASVS V2.1.8",
    details: "Invocado no fluxo de logout em todos os dispositivos, troca de senha e desativação por SuperAdmin.",
  },
  {
    id: "BE-MAP-003",
    technicalName: "Supabase SQL Editor - Execute Sessions & Security Audit DDL with RLS",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 24h",
    description: "Criação das tabelas 'sessions' e 'security_audit_events' com índices de alta performance e políticas de Row Level Security no PostgreSQL.",
    affectedFile: "Supabase PostgreSQL Database",
    compliance: "OWASP Top 10 A01:2021 (Broken Access Control)",
    details: "Executar script SQL fornecido no aba de Correções Necessárias pelo SQL Editor do Supabase.",
  },
  {
    id: "BE-MAP-004",
    technicalName: "loginRateLimiter.js - Token Bucket / Sliding Window Brute-Force Shield",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 4h",
    description: "Limitador de taxa de requisições de login por IP e credencial com bloqueio progressivo e resposta HTTP 429 Too Many Requests.",
    affectedFile: "src/security/loginRateLimiter.js",
    compliance: "RFC 6585 / NIST SP 800-63B Section 5.2.2",
    details: "Máximo de 5 tentativas consecutivas por janela de 15 minutos.",
  },
  {
    id: "BE-MAP-005",
    technicalName: "apiSchemas.ts - Strict Server-Side Zod Schemas (.strip() Anti-Mass Assignment)",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Schemas Zod para todas as rotas (Auth, Appointments, POS, Services, Clients) com .strip() compulsório e tipagem rigorosa.",
    affectedFile: "src/schemas/apiSchemas.ts",
    compliance: "OWASP Top 10 A04:2021 / OWASP ASVS v4.0 V5.1 (Input Validation)",
    details: "Expurgo imediato de propriedades não declaradas (como role, tenant_id ou balance) e validação de formatos (UUID v4, e-mail, HH:MM).",
  },
  {
    id: "BE-MAP-006",
    technicalName: "zodValidationMiddleware.ts - Generic Zod Input Validation & Payload Size Guard (256KB)",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Middleware genérico de validação com verificação de tamanho de payload (256KB DoS guard) e respostas HTTP 400 padronizadas.",
    affectedFile: "src/middleware/zodValidationMiddleware.ts",
    compliance: "OWASP ASVS V5.1 / CWE-915 (Mass Assignment) / RFC 7231",
    details: "Intercepta body, query, params e headers substituindo req.* pelos dados sanitizados sem vazar detalhes internos.",
  },
  {
    id: "BE-MAP-007",
    technicalName: "appointmentsEndpoint.js - Integrated Request Validation with Zod Stripping",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 4h",
    description: "Integração do validador Zod em rotas mutáveis de agendamento (PUT/PATCH), impedindo sobrescrita de tenant_id ou campos arbitrários.",
    affectedFile: "src/api/appointmentsEndpoint.js",
    compliance: "OWASP ASVS V5.1 / BOLA Mitigation",
    details: "Garante sanitização completa antes de qualquer mutação de estado em agendamentos.",
  },
  {
    id: "BE-MAP-008",
    technicalName: "atomicBookingService.ts - Atomic RPC PostgreSQL & Advisory Lock Concurrency Defense",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Invocação segura da RPC 'book_appointment_atomic' no PostgreSQL com bloqueio explícito FOR UPDATE, advisory lock determinístico e prevenção comprovada de double booking.",
    affectedFile: "src/api/atomicBookingService.ts",
    compliance: "ACID Transactions / RFC 7231 (HTTP 409 Conflict) / OWASP Top 10 A04:2021",
    details: "Protege agendamentos simultâneos no mesmo slot. Executa retry automático com exponential backoff e random jitter (20-60ms).",
  },
  {
    id: "BE-MAP-009",
    technicalName: "Supabase SQL Editor - Execute Atomic Booking RPC & GiST Range Exclusion DDL",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 24h",
    description: "Criação da extensão btree_gist, restrição de exclusão de horários sobrepostos e função RPC 'book_appointment_atomic' no PostgreSQL do Supabase.",
    affectedFile: "supabase/migrations/20260925_rpc_atomic_booking_race_condition.sql",
    compliance: "ACID Isolation / PostgreSQL GiST Exclusion Constraints",
    details: "Executar o script SQL da migração 20260925_rpc_atomic_booking_race_condition.sql no SQL Editor do Supabase.",
  },
  {
    id: "BE-MAP-010",
    technicalName: "apiDispatcher.ts - HTTP Concurrency Defense & Slot Overlap Rejection",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Roteamento em apiDispatcher conectando POST /api/appointments ao motor atômico com resposta HTTP 201 no agendamento vencedor e 409 nas colisões.",
    affectedFile: "src/api/apiDispatcher.ts",
    compliance: "OWASP Top 10 A04:2021 / RFC 7231 Section 6.5.8",
    details: "Validação estrita com schema Zod, serialização em tempo de execução e rota de auditoria GET /api/appointments/concurrency-audit.",
  },
  {
    id: "BE-MAP-011",
    technicalName: "test-atomic-concurrency-http.js - 10 Parallel HTTP Requests Audit & Validation Report",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Script Node.js disparando 10 requisições simultâneas via Promise.all, assertando 1 HTTP 201, 9 HTTP 409 e zero duplicidades no banco.",
    affectedFile: "scripts/test-atomic-concurrency-http.js",
    compliance: "ACID Isolation / Double Booking Prevention",
    details: "Gera relatório estruturado reports/concurrency-race-validation-report.json com métricas e latências individuais.",
  },
  {
    id: "BE-MAP-012",
    technicalName: "test-load.js - k6 PgBouncer Stress Testing Script (50 -> 500 VUs in 2 min)",
    squad: "QA, Performance & Security",
    squadIcon: "Target",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Script oficial k6 com rampa de carga progressiva (50 a 500 VUs), consultas mistas de leitura/escrita e thresholds automatizados de parada.",
    affectedFile: "test-load.js",
    compliance: "k6 Performance Testing / SRE Load Tolerances",
    details: "Configurado com abortOnFail: true se taxa de erros ultrapassar 1%, p(95) < 500ms e p(99) < 1500ms.",
  },
  {
    id: "BE-MAP-013",
    technicalName: "connectionPoolGuard.ts - PgBouncer Transaction Pooling & Connection Queue Manager",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 2h",
    description: "Gerenciador do pool de conexões operando em modo transaction pooling para suportar 500 VUs simultâneos com pool enxuto e proteção contra saturação.",
    affectedFile: "src/middleware/connectionPoolGuard.ts",
    compliance: "PgBouncer Architecture / High Concurrency Scalability",
    details: "Monitora filas de espera, conexões ativas e métricas percentílicas p50/p95/p99 em tempo real.",
  },
  {
    id: "BE-MAP-014",
    technicalName: "run-k6-load-benchmark.js - PgBouncer 500 VUs Benchmark & JSON SRE Report",
    squad: "QA, Performance & Security",
    squadIcon: "Target",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 2h",
    description: "Benchmark autônomo Node.js que simula 50 a 500 VUs com 2000 requisições e exporta relatório estruturado em reports/pgbouncer-k6-load-report.json.",
    affectedFile: "scripts/run-k6-load-benchmark.js",
    compliance: "SRE Load Standards / Automated APDEX Reporting",
    details: "Valida taxa de falhas (< 1.00%), p95 (< 500ms) e p99 (< 1500ms) com métricas consolidadas.",
  },
  {
    id: "BE-MAP-015",
    technicalName: "pgBouncerLoadK6.test.ts - Vitest Integration SLA & Threshold Validation",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: Automated CI/CD",
    description: "Suíte de testes de integração Vitest com Supertest validando resiliência sob carga simultânea, p95 e integridade do pool PgBouncer.",
    affectedFile: "src/tests/integration/pgBouncerLoadK6.test.ts",
    compliance: "Vitest SLA Validation / Connection Pool Integrity",
    details: "Executa ondas de 100+ requisições concorrentes mistas e garante zero erro 503.",
  },

  // ==========================================
  // SQUAD 4: DEVOPS, SRE & CLOUD INFRA
  // ==========================================
  {
    id: "DEV-MAP-001",
    technicalName: "Supabase CLI - Deploy Edge Functions (revoke-user-sessions & verify-jwt-session)",
    squad: "DevOps, SRE & Cloud Infra",
    squadIcon: "Rocket",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "HIGH (P1)",
    sla: "SLA: 24h",
    description: "Publicação das Edge Functions Deno no cluster Supabase via terminal com vinculação de segredos de serviço.",
    affectedFile: "supabase/functions/*",
    compliance: "Twelve-Factor App / Cloud Edge Security",
    details: "Executar: supabase functions deploy revoke-user-sessions && supabase functions deploy verify-jwt-session.",
  },
  {
    id: "DEV-MAP-002",
    technicalName: "Mercado Pago Developers - Obtain Production Access Token & Webhook Secret",
    squad: "DevOps, SRE & Cloud Infra",
    squadIcon: "Rocket",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 48h",
    description: "Geração de credenciais de produção no portal de desenvolvedores do Mercado Pago e configuração da URL de notificação de pagamentos Pix.",
    affectedFile: "Painel Mercado Pago (developers.mercadopago.com)",
    compliance: "PCI DSS / Payment Gateway Security",
    details: "Cadastrar endpoint HTTPS /api/webhooks/mercadopago e salvar MERCADO_PAGO_ACCESS_TOKEN no cofre seguro.",
  },
  {
    id: "DEV-MAP-003",
    technicalName: "vite.config.ts - Production Bundle Hygiene & Environment Boundary",
    squad: "DevOps, SRE & Cloud Infra",
    squadIcon: "Rocket",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "LOW (P3)",
    sla: "SLA: 24h",
    description: "Garantia de que apenas variáveis iniciadas com VITE_ sejam exportadas para o bundle do cliente e que segredos de serviço permaneçam isolados.",
    affectedFile: "vite.config.ts",
    compliance: "Twelve-Factor App III (Config)",
    details: "Auditoria contínua via suíte DEV-01 prevenindo vazamento de SERVICE_ROLE_KEY no bundle estático.",
  },
  {
    id: "DEV-MAP-004",
    technicalName: "Supabase Settings - Configure PgBouncer Connection Pooler (Port 6543, Transaction Mode)",
    squad: "DevOps, SRE & Cloud Infra",
    squadIcon: "Rocket",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 24h",
    description: "Habilitação e calibração do PgBouncer em modo Transaction Pooling com pool de 25-50 conexões e max client connections de 1000.",
    affectedFile: "Supabase Dashboard (Project Settings > Database)",
    compliance: "PgBouncer Architecture / High Concurrency Scalability",
    details: "Configurar DATABASE_URL em produção para usar porta 6543 com parâmetro ?pgbouncer=true.",
  },
  {
    id: "DEV-MAP-005",
    technicalName: "Supabase SQL Editor - Deploy book_appointment_atomic Function with Advisory Lock",
    squad: "DevOps, SRE & Cloud Infra",
    squadIcon: "Rocket",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 12h",
    description: "Execução do DDL da função RPC atômica com pg_try_advisory_xact_lock no SQL Editor do Supabase.",
    affectedFile: "Supabase Dashboard (SQL Editor)",
    compliance: "ACID Isolation / Race Condition Mitigation",
    details: "Compilar função PL/pgSQL e conceder permissões de execução aos papéis autorizados.",
  },

  // ==========================================
  // SQUAD 5: COMPLIANCE, DPO & LGPD
  // ==========================================
  {
    id: "CMP-MAP-001",
    technicalName: "masks.js - Sensitive Data PII Log Redaction Engine (CPF & Phone)",
    squad: "Compliance, DPO & LGPD",
    squadIcon: "Scale",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 6h",
    description: "Mecanismo de higienização de logs que mascara automaticamente dados pessoais identificáveis (PII) antes de qualquer persistência.",
    affectedFile: "src/utils/masks.js",
    compliance: "LGPD Art. 46 / GDPR Art. 32",
    details: "CPFs são transformados em '***.456.789-**' e telefones em '(11) *****-1234' nos logs do sistema.",
  },
  {
    id: "CMP-MAP-002",
    technicalName: "Data Protection Officer - ANPD Security Incident Response Registry",
    squad: "Compliance, DPO & LGPD",
    squadIcon: "Scale",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "MEDIUM (P2)",
    sla: "SLA: 72h",
    description: "Formalização do canal de comunicação do encarregado de dados (DPO) e registro das medidas de segurança perante a Autoridade Nacional.",
    affectedFile: "Portal Gov.br / ANPD",
    compliance: "LGPD Art. 41 & Art. 48",
    details: "Cadastrar e-mail dpo@barbeariasaas.com.br no portal oficial e vincular ao termo de privacidade do SaaS.",
  },
  {
    id: "CMP-MAP-003",
    technicalName: "securityAuditor.js - Immutable Audit Trail for Security Events",
    squad: "Compliance, DPO & LGPD",
    squadIcon: "Scale",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "MEDIUM (P2)",
    sla: "SLA: 8h",
    description: "Registro cronológico de ações administrativas de revogação de tokens, bloqueios de usuários e violações de controle de acesso.",
    affectedFile: "src/pages/QAPanel/securityAuditor.js",
    compliance: "OWASP ASVS V7.1 / LGPD Art. 37",
    details: "Eventos imutáveis com timestamp ISO, ator responsável e metadados contextuais para auditoria forense.",
  },
  {
    id: "CMP-MAP-004",
    technicalName: "auditTrailEngine.ts - Immutable Audit Trail (WORM) & PG Triggers Engine",
    squad: "Compliance, DPO & LGPD",
    squadIcon: "Scale",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Sistema de trilha de auditoria contendo os 8 campos canônicos obrigatórios, verificação criptográfica SHA-256 HMAC anti-tamper e bloqueio de UPDATE/DELETE.",
    affectedFile: "src/security/auditTrailEngine.ts",
    compliance: "WORM / LGPD Art. 37 / SOC 2 / PCI-DSS v4.0",
    details: "Validação estrita com teste de conformidade vitest e suíte interativa SEC-21 no QA Studio.",
  },
  {
    id: "CMP-MAP-005",
    technicalName: "Supabase SQL Editor - Executar Migração 20260925_immutable_audit_trail_system.sql",
    squad: "Compliance, DPO & LGPD",
    squadIcon: "Scale",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 12h",
    description: "Execução manual do script DDL de auditoria no painel Supabase para criar tabela audit_logs, triggers em appointments, transactions, profiles e tenants, e regras RLS WORM.",
    affectedFile: "Painel Supabase (SQL Editor -> 20260925_immutable_audit_trail_system.sql)",
    compliance: "LGPD Art. 37 / SOX Section 404",
    details: "Gera tabela audit_logs com RLS FORCED e triggers de negação de mutação BEFORE UPDATE/DELETE/TRUNCATE.",
  },
  {
    id: "CMP-MAP-006",
    technicalName: "lgpdPurgeEngine.ts - Soft-Delete (deleted_at), Cascade Hard-Delete & Fiscal Hash Anonymization",
    squad: "Compliance, DPO & LGPD",
    squadIcon: "Scale",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Mecanismo completo de descontinuação de dados de clientes: soft-delete com retenção temporária de 30 dias para recuperação, expurgo definitivo em cascata respeitando Foreign Keys e anonimização fiscal irreversível.",
    affectedFile: "src/security/lgpdPurgeEngine.ts",
    compliance: "LGPD Art. 16/18 / GDPR Art. 17 / CTN Art. 173",
    details: "Anonimização de CPF e Nome via hashes determinísticos SHA-256 com Pepper, preservando histórico contábil para o fisco.",
  },
  {
    id: "CMP-MAP-007",
    technicalName: "lgpd-purge-cron/index.ts & 20260925_lgpd_purge_and_anonymization_engine.sql - Supabase Edge Function & RPC",
    squad: "Compliance, DPO & LGPD",
    squadIcon: "Scale",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 4h",
    description: "Edge Function serverless e procedure PostgreSQL execute_lgpd_hard_delete_purge() para orquestração automática e periódica de expurgo e anonimização.",
    affectedFile: "supabase/functions/lgpd-purge-cron/index.ts",
    compliance: "LGPD Art. 16, I e IV / GDPR Art. 17",
    details: "Suporte a modo dry-run, métricas granulares de execução e verificação de integridade relacional.",
  },
  {
    id: "CMP-MAP-008",
    technicalName: "Painel Supabase - Ativar extensão pg_cron e Segredo LGPD_ANONYMIZATION_PEPPER no Vault",
    squad: "Compliance, DPO & LGPD",
    squadIcon: "Scale",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 24h",
    description: "Habilitação da extensão de agendamento pg_cron no painel do banco de dados e configuração da chave criptográfica de anonimização no cofre de segredos.",
    affectedFile: "Painel Supabase (Database -> Extensions / Vault)",
    compliance: "LGPD Art. 46 / CTN Art. 173",
    details: "Agendamento diário às 03:00 UTC para processamento assíncrono sem impacto de I/O em horários de pico.",
  },

  // ==========================================
  // SQUAD 6: DATA ENGINEERING & DBA
  // ==========================================
  {
    id: "DB-MAP-001",
    technicalName: "20260925_soft_delete_customers_structure.sql - Task 1.1: customers DDL & Partial Indexes",
    squad: "Data Engineering & DBA",
    squadIcon: "Database",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Migration DDL adicionando coluna deleted_at TIMESTAMPTZ e índices parciais de alta performance para registros ativos (WHERE deleted_at IS NULL) e inativos.",
    affectedFile: "supabase/migrations/20260925_soft_delete_customers_structure.sql",
    compliance: "LGPD Art. 16/18 / PostgreSQL 15+",
    details: "Índice parcial idx_customers_active_tenant garante leituras O(log n) desconsiderando registros excluídos.",
  },
  {
    id: "DB-MAP-002",
    technicalName: "active_customers VIEW - Transparent Exclusion Filter Abstraction (Task 1.1)",
    squad: "Data Engineering & DBA",
    squadIcon: "Database",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 2h",
    description: "View SQL public.active_customers encapsulando o filtro WHERE deleted_at IS NULL, evitando modificação de queries na aplicação.",
    affectedFile: "supabase/migrations/20260925_soft_delete_customers_structure.sql",
    compliance: "LGPD Art. 18 / ANSI SQL",
    details: "Permite que consultas de clientes continuem simples e padronizadas sem risco de expor tuplas descontinuadas.",
  },
  {
    id: "DB-MAP-003",
    technicalName: "soft_delete_customer(target_id UUID) - Stored Procedure with Permission Revocation (Task 1.2)",
    squad: "Data Engineering & DBA",
    squadIcon: "Database",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Stored procedure em PL/pgSQL que atualiza deleted_at = NOW() e revoga ativamente permissões e sessões ativas do cliente.",
    affectedFile: "supabase/migrations/20260925_soft_delete_customers_structure.sql",
    compliance: "LGPD Art. 18 / OWASP ASVS V2.1.8",
    details: "Invalida instantaneamente a tabela sessions e metadata em auth.users, além de cancelar agendamentos futuros pendentes.",
  },
  {
    id: "DB-MAP-004",
    technicalName: "Supabase SQL Editor - Executar Migração 20260925_soft_delete_customers_structure.sql",
    squad: "Data Engineering & DBA",
    squadIcon: "Database",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 12h",
    description: "Execução do script DDL de soft-delete, índices parciais, VIEW active_customers e stored procedure soft_delete_customer no banco Supabase.",
    affectedFile: "Painel Supabase (SQL Editor -> migrations)",
    compliance: "LGPD Art. 16/18 / GDPR Art. 17",
    details: "Gera a estrutura física otimizada e procedure segura com SECURITY DEFINER no PostgreSQL.",
  },
  {
    id: "DB-MAP-005",
    technicalName: "anonymize_customer_data(target_id UUID) - PL/pgSQL Function with pgcrypto (Task 2.1)",
    squad: "Data Engineering & DBA",
    squadIcon: "Database",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Função PL/pgSQL com extensão pgcrypto (digest sha256) substituindo nome, e-mail e CPF por hashes irreversíveis e zerando dados secundários (telefone, endereço).",
    affectedFile: "supabase/migrations/20260925_anonymize_customer_data_function.sql",
    compliance: "LGPD Art. 16, I / CTN Art. 173 / GDPR Art. 17",
    details: "Preserva o registro físico do cliente (id) e integridade com transações financeiras e pedidos históricos para guarda legal tributária de 5 anos.",
  },
  {
    id: "DB-MAP-006",
    technicalName: "customers & transactions Fiscal Consistency Schema - Preserving Historical Invoices & Orders",
    squad: "Data Engineering & DBA",
    squadIcon: "Database",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 4h",
    description: "Blindagem de integridade referencial que impede órfãos em pedidos e notas fiscais ao descontinuar dados cadastrais de clientes.",
    affectedFile: "src/security/lgpdPurgeEngine.ts",
    compliance: "CTN Art. 173 / LGPD Art. 16, I",
    details: "Validação bidirecional de que valores e identificadores de notas fiscais não sofram corrupção por exclusão física prematura.",
  },
  {
    id: "DB-MAP-007",
    technicalName: "Supabase SQL Editor - Habilitar pgcrypto e Executar Migração 20260925_anonymize_customer_data_function.sql",
    squad: "Data Engineering & DBA",
    squadIcon: "Database",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 12h",
    description: "Instalação da extensão pgcrypto e compilação da função PL/pgSQL anonymize_customer_data no cluster Supabase de produção.",
    affectedFile: "Painel Supabase (SQL Editor -> migrations)",
    compliance: "LGPD Art. 46 / CTN Art. 173",
    details: "Execução DDL com permissões GRANT EXECUTE para service_role e authenticated com SECURITY DEFINER.",
  },
  {
    id: "SEC-MAP-011",
    technicalName: "errorHandlerMiddleware.ts - Centralized Unhandled Exception Interceptor (CWE-209)",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 1h",
    description: "Middleware centralizado interceptando 100% de exceções não tratadas no Express e Edge Functions sem quebrar o event loop.",
    affectedFile: "src/middleware/errorHandlerMiddleware.ts",
    compliance: "CWE-209 / OWASP Top 10 A05:2021",
    details: "Padroniza respostas HTTP 500 com mensagem genérica segura e UUID v4 requestId.",
  },
  {
    id: "SEC-MAP-012",
    technicalName: "errorHandlerMiddleware.ts - HTTP 500 UUID requestId & Stack Trace Total Omission",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Eliminação total de stack traces, nomes de tabelas SQL, queries e variáveis de ambiente em respostas HTTP 500.",
    affectedFile: "src/middleware/errorHandlerMiddleware.ts",
    compliance: "OWASP ASVS V1.14 / CWE-209",
    details: "Injeção dos headers X-Request-Id e X-Content-Type-Options: nosniff para proteção dos clientes.",
  },
  {
    id: "SEC-MAP-013",
    technicalName: "secureLogger.ts - Recursive Data Scrubbing (password, credit_card, token, cpf)",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Configurador seguro de logging estilo Pino/Winston com redação recursiva de senhas, cartões de crédito (preserva 4 últimos dígitos), tokens e CPFs.",
    affectedFile: "src/utils/secureLogger.ts",
    compliance: "PCI-DSS v4.0 Req 6.5.5 / LGPD Art. 46",
    details: "Buffer circular em memória para observabilidade interna com stack traces isolados do público externo.",
  },
  {
    id: "SEC-MAP-014",
    technicalName: "errorHandlerMiddleware.ts - Supabase Edge Functions wrapEdgeFunctionHandler Wrapper",
    squad: "DevOps, SRE & Cloud Infra",
    squadIcon: "Rocket",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Wrapper assíncrono para Supabase Edge Functions (Deno / TypeScript) capturando crashes e gerando resposta 500 segura com X-Request-Id.",
    affectedFile: "src/middleware/errorHandlerMiddleware.ts",
    compliance: "Cloud Edge Security / OWASP A05",
    details: "Garante homogeneidade de tratamento de erros entre o backend Express e o cluster Deno.",
  },
  {
    id: "DEV-MAP-007",
    technicalName: "Supabase Logflare / Sentry - Configurar Data Scrubbing Rules e Alertas por requestId (EXT-SRE-01)",
    squad: "DevOps, SRE & Cloud Infra",
    squadIcon: "Shield",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 24h",
    description: "Configuração de regras de scrubbing no Sentry/Logflare do Supabase e Cloudflare WAF custom error pages para ocultar server tokens.",
    affectedTarget: "Painel Supabase (Settings -> Logs) & Sentry Dashboard",
    compliance: "CWE-209 / OWASP A05:2021 / PCI-DSS v4.0",
    details: "Vincula alertas do SRE ao requestId UUID com proteção de dados sensíveis.",
  },
  {
    id: "DEV-MAP-008",
    technicalName: "vite.config.ts - Disabling Source Maps in Production (build.sourcemap: false)",
    squad: "DevOps, SRE & Cloud Infra",
    squadIcon: "Rocket",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 4h",
    description: "Configuração estrita no vite.config.ts garantindo que nenhum arquivo .map de engenharia reversa seja exposto em produção.",
    affectedFile: "vite.config.ts",
    compliance: "OWASP ASVS v4.0 V14.2 / CWE-540",
    details: "Impede o vazamento de código TypeScript e estrutura interna da aplicação para o navegador.",
  },
  {
    id: "SEC-MAP-026",
    technicalName: "audit-bundle-secrets.js - Post-Build Bundle Leakage Scanner & Sanitized .env.example",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Script SecOps inspecionando todos os arquivos da pasta /dist procurando service_role, chaves privadas Stripe e tokens de pagamento.",
    affectedFile: "scripts/audit-bundle-secrets.js",
    compliance: "OWASP Top 10 A05:2021 / NIST SP 800-63B",
    details: "Gera dist/bundle-audit-report.json e bloqueia pipeline de CI/CD se qualquer credencial vazar.",
  },
  {
    id: "SEC-MAP-027",
    technicalName: "webhookHmacAndIdempotencyMiddleware.ts - HMAC-SHA256 Multi-Provider Verification (MP, Stripe, WhatsApp)",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Middleware de validação de assinatura criptográfica HMAC-SHA256 em tempo constante contra Timing Attacks (CWE-208) e janela de tolerância de 300s contra Replay Attacks.",
    affectedFile: "src/middleware/webhookHmacAndIdempotencyMiddleware.ts",
    compliance: "OWASP API Security Top 10 / RFC 2104 / CWE-208 / CWE-294",
    details: "Inspeciona raw body antes do JSON parse para prevenir Prototype Pollution. Suporta Mercado Pago (x-signature), Stripe (stripe-signature) e WhatsApp Cloud API.",
  },
  {
    id: "SEC-MAP-028",
    technicalName: "webhook_idempotency_keys - Atomic Concurrency Lock & Anti-Double Spending Fast ACK",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Controle de idempotência em banco com chave única composta {provider}:{event_id}, lock atômico de concorrência e retorno imediato de Fast ACK HTTP 200/202.",
    affectedFile: "src/middleware/webhookHmacAndIdempotencyMiddleware.ts",
    compliance: "IETF Webhook RFC / PCI-DSS v4.0 / CWE-362",
    details: "Desacopla tarefas demoradas em filas assíncronas e evita processamento duplicado de cobranças e créditos financeiros.",
  },
  {
    id: "EXT-MAP-011",
    technicalName: "Supabase Dashboard - Emergency service_role & JWT Secret Key Rotation (EXT-SEC-03)",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Protocolo de rotação da chave service_role e renovação do JWT secret no painel do Supabase com recarga em Edge Functions.",
    affectedTarget: "Painel Supabase (Project Settings -> API)",
    compliance: "OWASP ASVS v4.0 V2.1.8 / RFC 7519",
    details: "Acessar Settings > API > JWT Settings > Generate new secret e atualizar variáveis de backend.",
  },
  {
    id: "EXT-MAP-012",
    technicalName: "Mercado Pago & Stripe Dashboards - Server-Side Secrets Segregation (EXT-DEV-05)",
    squad: "DevOps, SRE & Cloud Infra",
    squadIcon: "Rocket",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 24h",
    description: "Configuração de chaves públicas no .env e segregação estrita de Access Tokens e Secret Keys no backend/Edge Functions.",
    affectedTarget: "Mercado Pago Developers & Stripe Dashboard",
    compliance: "PCI-DSS v4.0 Req 6.5.3 / OWASP A05",
    details: "Expor exclusivamente VITE_STRIPE_PUBLIC_KEY e manter STRIPE_SECRET_KEY como segredo isolado.",
  },
  {
    id: "FE-MAP-009",
    technicalName: "logoutService.ts - Centralized executeLogout & State Sanitization",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Função centralizada executeLogout() acionada na saída manual ou expiração de token com signOut() no Supabase e expurgo de memória.",
    affectedFile: "src/security/logoutService.ts",
    compliance: "OWASP ASVS v4.0 V3.3.4 / NIST SP 800-63B",
    details: "Garante encerramento determinístico com auditoria síncrona e desacoplamento de eventos.",
  },
  {
    id: "FE-MAP-010",
    technicalName: "queryClient.ts - React Query Complete Cache Invalidation (queryClient.clear())",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Invalidação e purga completa do cache em memória do TanStack React Query (queryClient.clear() e removeQueries()).",
    affectedFile: "src/lib/queryClient.ts",
    compliance: "OWASP Top 10 A01:2021 (Broken Access Control) / CWE-200",
    details: "Zera queries e mutações em memória, impedindo vazamento de agendamentos, clientes e finanças.",
  },
  {
    id: "FE-MAP-011",
    technicalName: "useSecureLogout.ts - Auto-Eviction on Token Expiration & Cross-Account Isolation",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 4h",
    description: "Hook React monitorando eventos de token expirado e orquestrando saída limpa com isolamento estrito entre contas no mesmo navegador.",
    affectedFile: "src/hooks/useSecureLogout.ts",
    compliance: "RFC 7009 / OWASP Session Management",
    details: "Impede que o login de um novo usuário herde dados residuais da conta anterior.",
  },
  {
    id: "SEC-MAP-009",
    technicalName: "logoutService.ts - Selective Storage Sanitization (LocalStorage & SessionStorage Zero-Leak)",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Higienização seletiva expurgando tokens, perfis e tenant IDs sem remover preferências neutras de UI (theme, locale).",
    affectedFile: "src/security/logoutService.ts",
    compliance: "OWASP ASVS V2.1.8 / NIST SP 800-63B 7.1",
    details: "Limpeza seletiva com whitelist explícita e expurgo total de sessionStorage.",
  },
  {
    id: "EXT-MAP-013",
    technicalName: "Supabase Auth - Enable Inactivity Timeout & Enforce Session Cutoff on Logout (EXT-SEC-04)",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 24h",
    description: "Configuração no painel Supabase para expiração por inatividade e gatilho de corte de sessão no PostgreSQL.",
    affectedTarget: "Painel Supabase (Authentication -> Settings)",
    compliance: "OWASP ASVS V3.3.4",
    details: "Ajustar Session Inactivity Timeout para 30 minutos e vincular trigger para inativar public.sessions.",
  },
  {
    id: "EXT-MAP-014",
    technicalName: "Mercado Pago Developers - Configurar Webhook Secret & IPN Endpoint (EXT-DEV-07)",
    squad: "DevOps, SRE & Cloud Infra",
    squadIcon: "Rocket",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 24h",
    description: "Geração da chave secreta x-signature no painel de desenvolvedores do Mercado Pago e cadastro da URL de notificação segura.",
    affectedTarget: "Painel Mercado Pago Developers (Webhooks)",
    compliance: "PCI-DSS v4.0 / HMAC-SHA256",
    details: "Acessar Mercado Pago Developers > Suas Aplicações > Notificações Webhook > Obter Chave Secreta HMAC.",
  },
  {
    id: "FE-MAP-012",
    technicalName: "apiContractValidator.ts - Zod Client-Side Contract Validation & Normalization",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Validação em runtime das cargas de API (serviços, barbeiros, agendamentos) utilizando schemas Zod com coerção de tipos e tolerância a contratos parciais antes de popular o estado do React.",
    affectedFile: "src/security/apiContractValidator.ts",
    compliance: "Robustness Principle / OWASP Top 10 A04:2021 / CWE-20",
    details: "Classifica os dados recebidos em INTACT, PARTIAL ou CORRUPTED com recuperação suave e registro de telemetria.",
  },
  {
    id: "FE-MAP-013",
    technicalName: "ErrorBoundary.tsx - React Component Error Containment & Graceful Recovery",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Componente React de Error Boundary para isolar falhas em módulos ou cards específicos sem derrubar a tela inteira da barbearia (anti-White Screen of Death).",
    affectedFile: "src/components/ui/ErrorBoundary.tsx",
    compliance: "React 19 Fault Tolerance / High Availability UI",
    details: "Implementa componentDidCatch, getDerivedStateFromError e callback de restauração interativa (retry/resetErrorBoundary).",
  },
  {
    id: "FE-MAP-014",
    technicalName: "ContractFallback.tsx - Visual Fallback Suite for Missing, Partial or Corrupted API Data",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 4h",
    description: "Conjunto de telas e badges visuais de contingência: DataCorruptedFallback, PartialDataNotice, EmptyDataFallback e ComponentCrashFallback.",
    affectedFile: "src/components/ui/ContractFallback.tsx",
    compliance: "WCAG 2.1 AA / UX Resilience & Graceful Degradation",
    details: "Exibe diagnósticos expansíveis do erro sem assustar o usuário e disponibiliza botões de retry.",
  },
  {
    id: "EXT-MAP-015",
    technicalName: "Supabase Database & API Gateway - Enforce Schema Constraints & Column Typing (EXT-API-01)",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "HIGH (P1)",
    sla: "SLA: 24h",
    description: "Alinhamento das colunas da tabela services, barbers e appointments no PostgreSQL para garantir integridade com o schema Zod (price >= 0, duration_minutes > 0).",
    affectedTarget: "Painel Supabase (Database -> Table Editor / SQL Editor)",
    compliance: "Data Integrity & Schema Versioning",
    details: "Adicionar restrições CHECK (price >= 0) e NOT NULL nos campos essenciais para prevenir divergências no client-side.",
  },
  {
    id: "SEC-MAP-020",
    technicalName: "security-bypass.spec.ts & routeSecurityGuard.ts - E2E Route Bypass & DOM Leak Prevention Suite",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Testes automatizados E2E (Playwright/Cypress) bloqueando acesso direto a /admin e /dashboard sem sessão e garantindo zero vazamento de dados confidenciais no DOM com redirecionamento imediato para login.",
    affectedFile: "tests/e2e/security-bypass.spec.ts",
    compliance: "OWASP Top 10 A01:2021 (Broken Access Control)",
    details: "Validação em pipeline de CI/CD garantindo isolamento total do DOM e bloqueio de requisições de API.",
  },
  {
    id: "FE-MAP-021",
    technicalName: "routeSecurityGuard.ts - LocalStorage Role Forgery & Anti-Tampering Protection",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Detecção e expurgo automático de manipulações manuais de privilégios no localStorage (role: 'admin') desprovidas de assinatura JWT legítima.",
    affectedFile: "src/security/routeSecurityGuard.ts",
    compliance: "OWASP Top 10 A07:2021 (Identification & Auth Failures)",
    details: "detectAndNeutralizeStorageTampering() limpa chaves forjadas e força redirecionamento para login.",
  },
  {
    id: "SRE-MAP-022",
    technicalName: "test-metrics-audit.js - PgBouncer Metrics Telemetry & Error Threshold < 1% (abortOnFail)",
    squad: "DevOps & SRE",
    squadIcon: "Zap",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Script de teste de carga em k6 calibrado para abortar imediatamente se connection_errors ou falhas HTTP ultrapassarem 1%, com SLA percentílico p95 < 500ms e p99 < 1500ms.",
    affectedFile: "test-metrics-audit.js",
    compliance: "SRE Operational Reliability & Tail Latency SLA",
    details: "Rampa com 80% GET e 20% POST instrumentando métricas customizadas para correlação com o PgBouncer.",
  },
  {
    id: "SRE-MAP-023",
    technicalName: "docs/pgbouncer-metrics-analysis-guide.md - PgBouncer vs Postgres Bottleneck Diagnostic Guide",
    squad: "DevOps & SRE",
    squadIcon: "Zap",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 4h",
    description: "Roteiro técnico e checklist de engenharia de performance para diagnosticar gargalos de PgBouncer (pool exhaustion) vs banco PostgreSQL (CPU/Disco) cruzando cl_active, cl_waiting, sv_active e sv_idle.",
    affectedFile: "docs/pgbouncer-metrics-analysis-guide.md",
    compliance: "Database Performance Engineering Framework",
    details: "Instruções CLI k6 com passagem de parâmetros via -e e matriz de decisão operacional para SRE.",
  },
  {
    id: "EXT-MAP-024",
    technicalName: "Supabase Dashboard & PgBouncer Admin Console - Real-Time Pool Sizing & Alerts (SHOW POOLS)",
    squad: "DevOps & SRE",
    squadIcon: "Zap",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 12h",
    description: "Habilitação de alertas de saturação de conexões no Supabase Dashboard e execução de SHOW POOLS; SHOW STATS; via console administrativo na porta 6543.",
    affectedTarget: "Painel Supabase (Database -> Reports / Connection Pooling)",
    compliance: "High Availability & Resource Sizing",
    details: "Configurar gatilho de alerta para cl_waiting > 0 por mais de 10s e monitorar consumo de CPU/IOPS.",
  },
  {
    id: "SEC-MAP-025",
    technicalName: "edgeSecurityHeaders.ts - Strict Content-Security-Policy & HSTS Preload Enforcement",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Camada de headers HTTP mandatórios de borda incluindo CSP estrito (com wss://*.supabase.co e https://), HSTS 31536000, X-Frame-Options DENY, nosniff e strict-origin.",
    affectedFile: "src/security/edgeSecurityHeaders.ts",
    compliance: "OWASP Secure Headers Project / PCI-DSS 4.0 Req 6.4.3",
    details: "Validação automatizada de 100% dos cabeçalhos prevenindo XSS, Clickjacking, MIME Confusion e SSL Stripping.",
  },
  {
    id: "DEV-MAP-026",
    technicalName: "vercel.json / _headers / netlify.toml - Multi-Platform Edge CDN Security Rules",
    squad: "DevOps & SRE",
    squadIcon: "Cloud",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Arquivos de infraestrutura de borda gerados para deploy em Vercel, Cloudflare Pages e Netlify injetando headers HTTP em todas as rotas com cache imutável em /assets.",
    affectedFile: "vercel.json, _headers & netlify.toml",
    compliance: "OWASP ASVS v4.0 V14 (Configuration)",
    details: "Compatibilidade integral com roteamento SPA e tolerância zero a vazamentos de cabeçalhos.",
  },
  {
    id: "EXT-MAP-027",
    technicalName: "Cloudflare Transform Rules & HSTS Preload - Global Edge Response Headers Injection",
    squad: "DevOps & SRE",
    squadIcon: "Cloud",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "HIGH (P1)",
    sla: "SLA: 12h",
    description: "Configuração de Transform Rules no dashboard Cloudflare para injeção de headers na CDN e submissão do domínio na lista global hstspreload.org.",
    affectedTarget: "Painel Cloudflare (Rules -> Transform Rules) / hstspreload.org",
    compliance: "Google Chrome HSTS Preload Standard / DNSSEC Validation",
    details: "Injeção de cabeçalhos estáticos nos PoPs globais e ativação de assinatura criptográfica DNSSEC.",
  },
  {
    id: "DEV-MAP-028",
    technicalName: "multiTierRateLimiter.ts - Multi-Tier Sensitive Route Rate Limiting (/auth/login, /api/payment, /api/*)",
    squad: "DevOps & SRE",
    squadIcon: "Zap",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Rate limiting estrito em nível de aplicação com /auth/login (5/min), /api/payment (10/min) e /api/* (100/min), retornando HTTP 429 e cabeçalho RFC Retry-After.",
    affectedFile: "src/middleware/multiTierRateLimiter.ts",
    compliance: "RFC 6585 / IETF RateLimit Headers / OWASP Automated Threats Mitigation",
    details: "Sliding window log com token bucket em memória, suporte a proxies reversos (CF-Connecting-IP, X-Forwarded-For) e adaptadores Express / Supabase Edge.",
  },
  {
    id: "DEV-MAP-029",
    technicalName: "cloudflare-rate-limiting-rules.json - Edge Gateway WAF Volumetric Rate Limiting Ruleset",
    squad: "DevOps & SRE",
    squadIcon: "Cloud",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Regras declarativas prontas para deploy no Cloudflare WAF com limite global de 300 req/min por IP e contenção de brute force nos 300+ PoPs Anycast.",
    affectedFile: "cloudflare-rate-limiting-rules.json",
    compliance: "Cloudflare Ruleset Engine v4 / OWASP Top 10 A04",
    details: "Ações automatizadas de 'block' com HTTP 429 para rotas sensíveis e 'managed_challenge' para proteção DDoS global.",
  },
  {
    id: "EXT-MAP-030",
    technicalName: "Cloudflare WAF Rulesets & Redis Cluster - Edge Rate Limiting & Distributed Counter Store",
    squad: "DevOps & SRE",
    squadIcon: "Cloud",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "HIGH (P1)",
    sla: "SLA: 8h",
    description: "Importação das regras no painel Cloudflare WAF e provisionamento de cluster Redis/Upstash para contagem atômica distribuída entre réplicas.",
    affectedTarget: "Painel Cloudflare (Security -> WAF -> Rate Limiting) / Upstash Console",
    compliance: "PCI-DSS 4.0 Req 6.4.2 / High Availability Architecture",
    details: "Centralização de contadores em memória com latência < 2ms para contenção de tráfego volumétrico em alta escala.",
  },
  {
    id: "SEC-MAP-031",
    technicalName: "DevSecOps CI/CD Pipeline - GitHub Actions Automated Security Workflow (.github/workflows/security.yml)",
    squad: "DevOps & SRE",
    squadIcon: "Rocket",
    status: "APROVADO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Workflow automatizado no GitHub Actions para Pull Requests com execução de Gitleaks, TruffleHog, Semgrep, SonarCloud, npm audit e Snyk.",
    affectedTarget: ".github/workflows/security.yml",
    compliance: "OWASP Top 10 / NIST SP 800-218 Secure Software Development Framework (SSDF)",
    details: "Quality gate estrito com exit 1 que bloqueia merge no Pull Request caso vulnerabilidades High ou Critical sejam detectadas.",
  },
  {
    id: "DEV-MAP-032",
    technicalName: "SAST & Secret Scanning Enforcement - Semgrep Rules, Gitleaks Policy & Strict Merge Quality Gate",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "APROVADO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Políticas de varredura estática de código (SAST) e segredos (.gitleaks.toml, .semgrepignore, cicdSecurityScanner.ts) protegendo a base de código.",
    affectedTarget: ".gitleaks.toml / .semgrepignore / src/security/cicdSecurityScanner.ts",
    compliance: "CIS Software Supply Chain Security Benchmark v1.0",
    details: "Bloqueio automático de credenciais vazadas (AWS, Stripe, Mercado Pago, chaves privadas) e análise de vulnerabilidades de código.",
  },
  {
    id: "EXT-MAP-033",
    technicalName: "GitHub Repository Branch Protection & CI Secrets Configuration (SNYK_TOKEN, SONAR_TOKEN)",
    squad: "DevOps & SRE",
    squadIcon: "Cloud",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "HIGH (P1)",
    sla: "SLA: 8h",
    description: "Configuração dos Secrets no GitHub Repository (SNYK_TOKEN, SONAR_TOKEN) e ativação de Branch Protection Rules com status checks obrigatórios.",
    affectedTarget: "GitHub Repository Settings -> Branches -> Branch protection rules & Secrets/Actions",
    compliance: "ISO 27001 A.14.2.8 / SOC 2 Type II Supply Chain Integrity",
    details: "Exigência de aprovação da pipeline 'DevSecOps Merge Quality Gate Enforcement' para autorizar merges em main/master.",
  },
  // ==========================================
  // SQUAD 5: FRONT-END & UI/UX - RESILIÊNCIA (PROMPT 25)
  // ==========================================
  {
    id: "RES-MAP-001",
    technicalName: "SkeletonCard.jsx & SkeletonBookingView.jsx - Skeletons para Alta Latência (>1200ms)",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "APROVADO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 24h",
    description: "Componentes modulares de Skeleton Screen fornecendo feedback visual imediato em 4 variantes (service, barber, appointment, metric) e wizard completo.",
    affectedTarget: "src/components/resilience/SkeletonCard.jsx / SkeletonBookingView.jsx",
    compliance: "Core Web Vitals (CLS = 0, INP < 200ms) / Google Material Skeleton",
    details: "Elimina telas brancas durante chamadas lentas ou conexões 3G, mantendo a sensação de resposta instantânea.",
  },
  {
    id: "RES-MAP-002",
    technicalName: "OfflineBanner.jsx & useNetworkResilience.js - Indicador 'Modo Offline / Reconectando...'",
    squad: "Front-End & UI/UX",
    squadIcon: "Radio",
    status: "APROVADO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 12h",
    description: "Banner discreto no topo da aplicação acionado ao perder a rede ou desconectar o WebSocket do Supabase Realtime, com botão de reconexão manual.",
    affectedTarget: "src/components/resilience/OfflineBanner.jsx / useNetworkResilience.js",
    compliance: "WCAG 2.1 4.1.3 Status Messages / Supabase Realtime Protocol / RFC 6455",
    details: "Indica 'Modo Offline / Reconectando...' assegurando ao usuário que seus dados estão preservados localmente.",
  },
  {
    id: "RES-MAP-003",
    technicalName: "ResilientFormHandler.jsx - Retenção de Formulário & Recuperação com 'Tentar Novamente'",
    squad: "Front-End & UI/UX",
    squadIcon: "FileText",
    status: "APROVADO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 12h",
    description: "Tratamento amigável de falhas de rede retendo 100% dos dados preenchidos em memória e sessionStorage, permitindo reenvio sem perda.",
    affectedTarget: "src/components/resilience/ResilientFormHandler.jsx",
    compliance: "Zero Data Loss Principle / Nielsen Norman Group Usability Heuristics #9",
    details: "Fornece botão de 'Tentar Novamente' e 'Editar Dados', eliminando a frustração de preenchimento redundante.",
  },
  {
    id: "RES-MAP-004",
    technicalName: "SkeletonDashboard.jsx - Esqueleto Suave para Carregamento de Métricas e Dashboards",
    squad: "Front-End & UI/UX",
    squadIcon: "BarChart3",
    status: "APROVADO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 24h",
    description: "Layout de carregamento suave para o BarbershopDashboard e métricas analíticas em redes instáveis.",
    affectedTarget: "src/components/resilience/SkeletonDashboard.jsx",
    compliance: "SRE Dashboard Design Guidelines",
    details: "Renderiza placeholders dimensionais para Big Numbers, gráficos e listagens sem saltos de página.",
  },
  {
    id: "SEC-MAP-032",
    technicalName: "ssrfProtectionEngine.ts - Prevenção de SSRF & Bloqueio de Metadados Cloud 169.254.169.254",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "APROVADO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Cliente SafeFetch impedindo conexões para 169.254.169.254, RFC 1918 e restringindo tráfego à allowlist estrita.",
    affectedTarget: "src/security/ssrfProtectionEngine.ts",
    compliance: "OWASP Top 10 A10:2021 (CWE-918) / NIST SP 800-53 SC-7",
    details: "Validação síncrona com mitigação de DNS Rebinding e bloqueio em tempo de compilação.",
  },
  // ==========================================
  // SQUAD 6: FRONT-END & ACESSIBILIDADE DIGITAL (WCAG 2.2 AA)
  // ==========================================
  {
    id: "A11Y-MAP-001",
    technicalName: "index.css / ServiceCard.jsx - Navegação 100% Funcional via Teclado e Indicadores :focus-visible",
    squad: "Front-End & UI/UX",
    squadIcon: "Accessibility",
    status: "APROVADO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 4h",
    description: "Ordem lógica de tabIndex, suporte às teclas Enter e Espaço em todos os cards interativos, anéis de foco dourados :focus-visible de 2px e link skip-to-content no topo.",
    affectedTarget: "src/index.css / ServiceCard.jsx / ProfessionalCard.jsx / Navbar.jsx",
    compliance: "WCAG 2.2 Critérios 2.1.1 (Teclado), 2.4.7 (Foco Visível) e 2.4.11 (Foco Não Obscurecido)",
    details: "Permite controle total do fluxo de agendamento exclusivamente via teclado sem dependência de ponteiro.",
  },
  {
    id: "A11Y-MAP-002",
    technicalName: "theme.js - Validação Algorítmica e Calibração de Contraste Cromático Mínimo 4.5:1",
    squad: "Front-End & UI/UX",
    squadIcon: "Accessibility",
    status: "APROVADO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 4h",
    description: "Garantia matemática de contraste mínimo de 4.5:1 para texto normal e 3.0:1 para elementos de interface via algoritmo oficial de luminância relativa W3C.",
    affectedTarget: "src/utils/theme.js / src/components/ui/Input.styles.js",
    compliance: "WCAG 2.2 Critério 1.4.3 (Contraste Mínimo AA) e 1.4.11 (Contraste Não-Textual)",
    details: "Validação sRGB com linearização gamma em runtime; temas Dark e Light com ratios entre 5.8:1 e 19.8:1.",
  },
  {
    id: "A11Y-MAP-003",
    technicalName: "OfflineBanner.jsx / ResilientFormHandler.jsx - Semântica WAI-ARIA Dinâmica e Regiões Vivas",
    squad: "Front-End & UI/UX",
    squadIcon: "Accessibility",
    status: "APROVADO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 12h",
    description: "Atributos ARIA adequados para regiões ativas em tempo real (role='status', aria-live='polite' e assertive), menus expansíveis e erros vinculados via aria-describedby.",
    affectedTarget: "src/components/resilience/OfflineBanner.jsx / ResilientFormHandler.jsx / Input.jsx",
    compliance: "WAI-ARIA 1.2 / WCAG 2.2 Critérios 4.1.2 (Name, Role, Value) e 4.1.3 (Status Messages)",
    details: "Anuncia atualizações de conectividade e alertas imediatamente aos leitores de tela sem interrupções destrutivas.",
  },
  {
    id: "A11Y-MAP-004",
    technicalName: "index.css - Conformidade com o Critério 2.5.8 da WCAG 2.2 (Target Size Mínimo de 24x24px)",
    squad: "Front-End & UI/UX",
    squadIcon: "Accessibility",
    status: "APROVADO",
    scope: "IN_PROJECT",
    severity: "MEDIUM (P2)",
    sla: "SLA: 24h",
    description: "Regra CSS global impondo min-height: 24px e min-width: 24px em botões, links, inputs, selects e elementos interativos.",
    affectedTarget: "src/index.css / src/components/ui/Button.styles.js / DatePicker.jsx",
    compliance: "WCAG 2.2 Critério 2.5.8 (Target Size - Minimum AA)",
    details: "Previne toques acidentais em mobile e garante acessibilidade para usuários com tremores motores.",
  },
  {
    id: "A11Y-MAP-005",
    technicalName: "wcagAccessibilityAudit.test.tsx - Suíte de Testes Automatizados no Vitest (13/13 Aprovados)",
    squad: "QA & Qualidade de Software",
    squadIcon: "FlaskConical",
    status: "APROVADO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: Automated CI/CD",
    description: "13 testes unitários e de integração cobrindo contraste numérico, navegação por teclado, tecla Escape, rótulos de calendário e semântica ARIA.",
    affectedTarget: "src/tests/unit/wcagAccessibilityAudit.test.tsx",
    compliance: "W3C WCAG 2.2 Level AA / Section 508",
    details: "100% aprovado no runner de testes automatizados com cobertura rigorosa dos 4 princípios fundamentais.",
  },
  // ==========================================
  // SQUAD: API MERCADO PAGO, PIX & WEBHOOKS
  // ==========================================
  {
    id: "MP-MAP-001",
    technicalName: "mercadoPagoEndpoints.ts - Handlers de API para Preference, Pix e Webhooks",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Handlers seguros server-side proxy para criação de preferências do Checkout Pro, emissão de Pix Instantâneo e recepção assíncrona de webhooks com validação Zod.",
    affectedFile: "src/api/mercadoPagoEndpoints.ts",
    compliance: "OWASP API Security Top 10 (API1:2023, API3:2023) / PCI-DSS v4.0",
    details: "Proxy server-side que elimina CORS e impede exposição de Access Token privado no cliente.",
  },
  {
    id: "MP-MAP-002",
    technicalName: "mercadoPagoService.ts - Checkout Pro, Pix EMVCo & Idempotência Anti-Double-Spending",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Serviço core integrando Checkout Pro, geração de payload EMVCo para Pix Instantâneo com QR Code vetorial SVG e chaves de idempotência anti-duplicidade.",
    affectedFile: "src/services/mercadoPagoService.ts",
    compliance: "Banco Central do Brasil (Pix EMVCo) / RFC 6749",
    details: "Suporte a credenciais Sandbox e Produção com chave seletora dinâmica e telemetria de status.",
  },
  {
    id: "MP-MAP-003",
    technicalName: "mercadoPagoSchemas.ts - Schemas Zod Estritos com .strip() contra Mass Assignment",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 2h",
    description: "Contratos Zod estritos com expurgo compulsório .strip() de propriedades arbitrárias injetadas em preferências e notificações de pagamento.",
    affectedFile: "src/schemas/mercadoPagoSchemas.ts",
    compliance: "OWASP Top 10 A04:2021 (Insecure Design) / CWE-915",
    details: "Garante integridade de valores monetários, identificadores de tenant e dados do pagador.",
  },
  {
    id: "MP-MAP-004",
    technicalName: "mercadoPagoLogger.ts - Telemetria de Transações e Mascaramento de Tokens",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "MEDIUM (P2)",
    sla: "SLA: 4h",
    description: "Logger seguro de auditoria com mascaramento automático de credenciais (APP_USR-***), injeção de requestId único e rastreabilidade ponta a ponta.",
    affectedFile: "src/services/mercadoPagoLogger.ts",
    compliance: "PCI-DSS v4.0 Req 3.4 / LGPD Art. 46",
    details: "Zero vazamento de segredos em logs de console e exportações de telemetria.",
  },
  {
    id: "MP-MAP-005",
    technicalName: "webhookHmacMiddleware.ts - Validação Criptográfica HMAC-SHA256 Constant-Time & Anti-Replay",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Middleware interceptor validando assinatura x-signature via comparação em tempo constante (timingSafeEqual) e janela de tolerância de 300s contra Replay Attacks.",
    affectedFile: "src/middleware/webhookHmacMiddleware.ts",
    compliance: "CWE-208 (Timing Attack) / CWE-294 (Replay Attack) / OWASP A07",
    details: "Inspeção do buffer de raw body sem desserialização prévia para garantia de autenticidade estrita.",
  },
  {
    id: "MP-MAP-006",
    technicalName: "webhookIdempotencyEngine.ts - Deduplicação Atômica com Locks e Fast ACK HTTP 200",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Mecanismo atômico de idempotência com locks em memória (L1) e chave composta (provider:dataId:eventId), prevenindo double spending e retornando Fast ACK.",
    affectedFile: "src/security/webhookIdempotencyEngine.ts",
    compliance: "IETF Idempotency-Key Standard / RFC 7231",
    details: "Elimina duplicidade de liberação de comissões de barbeiros e confirmações de planos repetidas.",
  },
  {
    id: "MP-MAP-007",
    technicalName: "MercadoPagoCheckoutModal.tsx - Modal Acessível de Checkout Pro e Pix com QR Code SVG",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "HIGH (P1)",
    sla: "SLA: 4h",
    description: "Interface do usuário em React com suporte a Pix Instantâneo (QR Code SVG + Copia e Cola com 1 clique), contador regressivo e polling de status em tempo real.",
    affectedFile: "src/components/payments/MercadoPagoCheckoutModal.tsx",
    compliance: "WCAG 2.2 AA / Mobile Ergonomics",
    details: "Feedback instantâneo de aprovação com região viva ARIA e contingência para oscilações de rede.",
  },
  {
    id: "MP-MAP-008",
    technicalName: "mercadoPagoApi.test.ts - Suíte de Testes Automatizados da API Mercado Pago no Vitest",
    squad: "QA & Qualidade de Software",
    squadIcon: "FlaskConical",
    status: "APROVADO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: Automated CI/CD",
    description: "Bateria de testes unitários e de integração cobrindo criação de preferências para planos Starter/Pro/Enterprise, Pix EMVCo e proteção de segredos.",
    affectedFile: "src/tests/unit/mercadoPagoApi.test.ts",
    compliance: "Vitest Testing Framework / CI/CD Quality Gate",
    details: "100% dos testes aprovados com validação de contratos Zod e mitigação de vulnerabilidades.",
  },
  {
    id: "MP-MAP-009",
    technicalName: "webhookHmacIdempotency.test.ts - Suíte de Assinatura HMAC e Tolerância de 300s no Vitest",
    squad: "QA & Qualidade de Software",
    squadIcon: "FlaskConical",
    status: "APROVADO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: Automated CI/CD",
    description: "Testes automatizados cobrindo rejeição de assinaturas falsificadas, tolerância temporal de 300 segundos e deduplicação de webhooks concorrentes.",
    affectedFile: "src/tests/unit/webhookHmacIdempotency.test.ts",
    compliance: "OWASP ASVS v4.0 / RFC 2104 (HMAC)",
    details: "Validação rigorosa contra ataques de canal lateral e replay de pacotes.",
  },
  {
    id: "MP-MAP-010",
    technicalName: "Supabase SQL Editor - Criar Tabela webhook_events com Restrição UNIQUE em idempotency_key",
    squad: "Data Engineering & DBA",
    squadIcon: "Database",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 12h",
    description: "Execução do script SQL DDL no painel Supabase para criar tabela webhook_events com restrição UNIQUE em idempotency_key e políticas RLS de service_role.",
    affectedTarget: "Painel Supabase (SQL Editor -> public.webhook_events)",
    compliance: "PCI-DSS v4.0 / SOC 2 Type II",
    details: "Script pronto para uso disponível no Console de Logs & Correções da Squad de Banco de Dados.",
  },
  {
    id: "MP-MAP-011",
    technicalName: "Supabase SQL Editor - Criar Tabela payments com Isolamento RLS Multi-Tenant",
    squad: "Data Engineering & DBA",
    squadIcon: "Database",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "HIGH (P1)",
    sla: "SLA: 12h",
    description: "Criação da tabela payments com Foreign Keys para tenants, ENUMs de status e políticas RLS garantindo isolamento absoluto entre barbearias.",
    affectedTarget: "Painel Supabase (SQL Editor -> public.payments)",
    compliance: "OWASP Top 10 A01:2021 (Broken Access Control)",
    details: "Script DDL completo disponível na aba Logs & Correções.",
  },
  {
    id: "MP-MAP-012",
    technicalName: "Mercado Pago Developers - Cadastrar URL do Webhook Oficial e Capturar Chave x-signature",
    squad: "DevOps, SRE & Cloud Infra",
    squadIcon: "Cloud",
    status: "PENDENTE_EXTERNA",
    scope: "EXTERNAL",
    severity: "CRITICAL (P0)",
    sla: "SLA: 24h",
    description: "Configuração da URL pública de produção no painel mercadopago.com.br/developers com seleção dos eventos payment e preapproval, e configuração do segredo HMAC.",
    affectedTarget: "Painel Mercado Pago Developers (Notificações Webhook)",
    compliance: "PCI-DSS v4.0 Req 6.4 / OWASP A07",
    details: "Instruções passo a passo guiadas disponíveis no Console de Logs & Correções.",
  },
  {
    id: "JWT-MAP-001",
    technicalName: "jwtService.ts - Assinatura HS256 & TTL Estrito (15m Access / 7d Refresh)",
    squad: "Cyber Security & AppSec",
    squadIcon: "Shield",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 1h",
    description: "Utilitários nativos em Node.js crypto assinando tokens HS256 com crypto.timingSafeEqual, Access Token (15m) e Refresh Token (7d) com claims de role e barbeariaId.",
    affectedFile: "src/services/jwtService.ts",
    compliance: "NIST SP 800-63B / RFC 7519 / OWASP Top 10 A07",
    details: "Claims de barbeariaId garantem isolamento multi-tenant absoluto.",
  },
  {
    id: "JWT-MAP-002",
    technicalName: "authController.ts - Controller de Login & Cookie HttpOnly com SameSite Strict",
    squad: "Back-End & Core APIs",
    squadIcon: "Settings",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Endpoint /api/auth/login emitindo Access Token no JSON e Refresh Token em Cookie HttpOnly com flags secure, sameSite: strict e maxAge de 7 dias.",
    affectedFile: "src/api/authController.ts",
    compliance: "OWASP ASVS v4.0 V3 (Session Management) / RFC 6265bis",
    details: "Impede completamente que scripts XSS acessem o Refresh Token no navegador.",
  },
  {
    id: "JWT-MAP-003",
    technicalName: "AuthContext.tsx - Access Token Estritamente em Memória RAM (useState)",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "Contexto React mantendo o Access Token em memória volátil (useState), blindando contra roubo via localStorage/sessionStorage e restaurando no F5 via useEffect.",
    affectedFile: "src/context/AuthContext.tsx",
    compliance: "OWASP Cheat Sheet Series (HTML5 Security / XSS Prevention)",
    details: "Silent Refresh automático na inicialização da aplicação.",
  },
  {
    id: "JWT-MAP-004",
    technicalName: "api.ts - Interceptadores Axios com Fila de Espera (Request Queuing) e Silent Refresh",
    squad: "Front-End & UI/UX",
    squadIcon: "Palette",
    status: "CORRIGIDO",
    scope: "IN_PROJECT",
    severity: "CRITICAL (P0)",
    sla: "SLA: 2h",
    description: "withCredentials: true global, injeção de Bearer token e tratamento transparente de HTTP 401 pausando a fila e reexecutando requisições após /refresh.",
    affectedFile: "src/services/api.ts",
    compliance: "Resilient Network Architecture / Zero Disruption UX",
    details: "Permite que a recepção e o painel fiquem abertos o dia todo sem deslogar.",
  },
];
