/**
 * @file ProjectIcon.jsx
 * @description Componente unificado de ícones vetoriais SVG da biblioteca lucide-react (^1.48.0).
 * Herda por padrão a Paleta de Cores Oficial & Tokens de Design do projeto (Âmbar Nobre: #f59e0b / text-amber-500).
 * Substitui integralmente o uso de emojis por ícones vetoriais limpos, acessíveis e escaláveis.
 */

import React from 'react';
import * as LucideIcons from 'lucide-react';

/**
 * Mapeamento semântico completo de emojis para ícones oficiais da biblioteca lucide-react
 */
export const EMOJI_TO_ICON_MAP = {
  '✂️': 'Scissors',
  '✂': 'Scissors',
  '💈': 'Scissors',
  '🪑': 'Armchair',
  '📅': 'Calendar',
  '🗓️': 'Calendar',
  '🗓': 'Calendar',
  '🕒': 'Clock',
  '⏰': 'Clock',
  '⏱️': 'Clock',
  '⏱': 'Clock',
  '⏳': 'Hourglass',
  '👤': 'User',
  '👥': 'Users',
  '👑': 'Crown',
  '🛡️': 'Shield',
  '🛡': 'Shield',
  '🔒': 'Lock',
  '🔓': 'Unlock',
  '🔑': 'Key',
  '🚪': 'LogOut',
  '📞': 'Phone',
  '📱': 'Smartphone',
  '📲': 'Smartphone',
  '💰': 'DollarSign',
  '💵': 'DollarSign',
  '💳': 'CreditCard',
  '🧾': 'Receipt',
  '📋': 'ClipboardList',
  '➕': 'Plus',
  '🗑️': 'Trash2',
  '🗑': 'Trash2',
  '✏️': 'Edit3',
  '✏': 'Edit3',
  '📝': 'FileText',
  '📜': 'Scroll',
  '🏢': 'Building2',
  '🏪': 'Store',
  '🍺': 'Beer',
  '🍻': 'Beer',
  '🧴': 'Package',
  '📦': 'Package',
  '🏷️': 'Tag',
  '🏷': 'Tag',
  '🎟': 'Ticket',
  '🎟️': 'Ticket',
  '📢': 'Megaphone',
  '🔔': 'Bell',
  '💬': 'MessageSquare',
  '🗨': 'MessageSquare',
  '🗨️': 'MessageSquare',
  '👁': 'Eye',
  '👁️': 'Eye',
  '👁️🗨️': 'EyeOff',
  '💡': 'Lightbulb',
  '📊': 'BarChart3',
  '📈': 'TrendingUp',
  '📉': 'TrendingDown',
  '⚙️': 'Settings',
  '⚙': 'Settings',
  '🔧': 'Wrench',
  '💻': 'Laptop',
  '📍': 'MapPin',
  '📷': 'Camera',
  '📄': 'FileText',
  '🧪': 'FlaskConical',
  '⚡': 'Zap',
  '🚀': 'Rocket',
  '🔄': 'RefreshCw',
  '💾': 'Download',
  '📥': 'Download',
  '📤': 'Upload',
  '🔗': 'ExternalLink',
  '🎯': 'Target',
  '🏆': 'Award',
  '🎁': 'Gift',
  '🔥': 'Flame',
  '🔘': 'CircleDot',
  '🚨': 'AlertCircle',
  '🐛': 'Bug',
  '📬': 'Mail',
  '📧': 'Mail',
  '✉️': 'Mail',
  '✉': 'Mail',
  '⭐': 'Star',
  '🌟': 'Star',
  '★': 'Star',
  '✨': 'Sparkles',
  '🎉': 'Sparkles',
  '🎨': 'Palette',
  '🔍': 'Search',
  '🔎': 'Search',
  '👋': 'UserCheck',
  '👈': 'ArrowLeft',
  '👉': 'ArrowRight',
  '👇': 'ArrowDown',
  '➔': 'ArrowRight',
  '→': 'ArrowRight',
  '←': 'ArrowLeft',
  '↔': 'MoveHorizontal',
  '✓': 'Check',
  '✔': 'Check',
  '✔️': 'Check',
  '✅': 'Check',
  '❌': 'X',
  '✕': 'X',
  '⚠️': 'AlertTriangle',
  '⚠': 'AlertTriangle',
  'ℹ️': 'Info',
  'ℹ': 'Info',
  '♿': 'ShieldCheck',
  '☀️': 'Sun',
  '☀': 'Sun',
  '🟢': 'CheckCircle2',
  '🔴': 'AlertCircle',
  '🟡': 'Clock',
  '⚪': 'Circle',
  '▲': 'ChevronUp',
  '▼': 'ChevronDown',
  '▶': 'Play',
  '▶️': 'Play',
  '⏸': 'Pause',
  '🤖': 'Bot',
  '📚': 'BookOpen',
  '📁': 'Folder',
  '🗄️': 'Database',
  '🗄': 'Database',
  '🏛️': 'Building2',
  '🏛': 'Building2',
  '🖧': 'Network',
  '⚖️': 'Scale',
  '⚖': 'Scale',
  '💉': 'Syringe',
  '🐘': 'Database',
  '🌈': 'Palette',
  '🛠️': 'Wrench',
  '🛠': 'Wrench',
  '💀': 'Skull',
  '💥': 'Zap',
  '🎭': 'UserCheck',
  '🖥️': 'Monitor',
  '🖥': 'Monitor',
  '🗖': 'AppWindow',
  '🧼': 'Sparkles',
  '🔐': 'Lock',
  '📑': 'FileText',
  '☁️': 'Cloud',
  '☁': 'Cloud',
};

/**
 * Mapeamento semântico de ícones frequentes do SaaS Barbearia
 */
export const ICON_MAP = {
  scissors: LucideIcons.Scissors,
  haircut: LucideIcons.Scissors,
  barber: LucideIcons.UserCheck,
  calendar: LucideIcons.Calendar,
  clock: LucideIcons.Clock,
  user: LucideIcons.User,
  users: LucideIcons.Users,
  crown: LucideIcons.Crown,
  shield: LucideIcons.Shield,
  shieldCheck: LucideIcons.ShieldCheck,
  shieldAlert: LucideIcons.ShieldAlert,
  lock: LucideIcons.Lock,
  unlock: LucideIcons.Unlock,
  key: LucideIcons.Key,
  login: LucideIcons.LogIn,
  logout: LucideIcons.LogOut,
  phone: LucideIcons.Phone,
  smartphone: LucideIcons.Smartphone,
  dollar: LucideIcons.DollarSign,
  dollarSign: LucideIcons.DollarSign,
  wallet: LucideIcons.Wallet,
  creditCard: LucideIcons.CreditCard,
  receipt: LucideIcons.Receipt,
  ticket: LucideIcons.Ticket,
  plus: LucideIcons.Plus,
  trash: LucideIcons.Trash2,
  trash2: LucideIcons.Trash2,
  edit: LucideIcons.Edit3,
  edit3: LucideIcons.Edit3,
  check: LucideIcons.Check,
  checkCircle: LucideIcons.CheckCircle2,
  checkCircle2: LucideIcons.CheckCircle2,
  close: LucideIcons.X,
  x: LucideIcons.X,
  alert: LucideIcons.AlertTriangle,
  alertTriangle: LucideIcons.AlertTriangle,
  alertCircle: LucideIcons.AlertCircle,
  info: LucideIcons.Info,
  sparkles: LucideIcons.Sparkles,
  palette: LucideIcons.Palette,
  dashboard: LucideIcons.LayoutDashboard,
  store: LucideIcons.Store,
  building: LucideIcons.Building2,
  building2: LucideIcons.Building2,
  beer: LucideIcons.Beer,
  wine: LucideIcons.Wine,
  product: LucideIcons.Package,
  package: LucideIcons.Package,
  tag: LucideIcons.Tag,
  star: LucideIcons.Star,
  search: LucideIcons.Search,
  settings: LucideIcons.Settings,
  wrench: LucideIcons.Wrench,
  terminal: LucideIcons.Terminal,
  fileText: LucideIcons.FileText,
  clipboardList: LucideIcons.ClipboardList,
  flask: LucideIcons.FlaskConical,
  zap: LucideIcons.Zap,
  rocket: LucideIcons.Rocket,
  barChart: LucideIcons.BarChart3,
  barChart3: LucideIcons.BarChart3,
  trendingUp: LucideIcons.TrendingUp,
  trendingDown: LucideIcons.TrendingDown,
  refresh: LucideIcons.RefreshCw,
  refreshCw: LucideIcons.RefreshCw,
  copy: LucideIcons.Copy,
  download: LucideIcons.Download,
  upload: LucideIcons.Upload,
  externalLink: LucideIcons.ExternalLink,
  layers: LucideIcons.Layers,
  server: LucideIcons.Server,
  network: LucideIcons.Network,
  filter: LucideIcons.Filter,
  award: LucideIcons.Award,
  gift: LucideIcons.Gift,
  bell: LucideIcons.Bell,
  message: LucideIcons.MessageSquare,
  messageSquare: LucideIcons.MessageSquare,
  flame: LucideIcons.Flame,
  target: LucideIcons.Target,
  circleDot: LucideIcons.CircleDot,
  sliders: LucideIcons.Sliders,
  percent: LucideIcons.Percent,
  shoppingBag: LucideIcons.ShoppingBag,
  menu: LucideIcons.Menu,
  home: LucideIcons.Home,
  chevronRight: LucideIcons.ChevronRight,
  chevronDown: LucideIcons.ChevronDown,
  chevronLeft: LucideIcons.ChevronLeft,
  chevronUp: LucideIcons.ChevronUp,
  chevronsUpDown: LucideIcons.ChevronsUpDown,
  arrowRight: LucideIcons.ArrowRight,
  arrowLeft: LucideIcons.ArrowLeft,
  arrowUp: LucideIcons.ArrowUp,
  arrowDown: LucideIcons.ArrowDown,
  arrowUpDown: LucideIcons.ArrowUpDown,
  moveHorizontal: LucideIcons.MoveHorizontal,
  eye: LucideIcons.Eye,
  eyeOff: LucideIcons.EyeOff,
  send: LucideIcons.Send,
  save: LucideIcons.Save,
  bug: LucideIcons.Bug,
  lightbulb: LucideIcons.Lightbulb,
  mail: LucideIcons.Mail,
  coffee: LucideIcons.Coffee,
  armchair: LucideIcons.Armchair,
  sunrise: LucideIcons.Sunrise,
  sun: LucideIcons.Sun,
  moon: LucideIcons.Moon,
  dices: LucideIcons.Dices,
  dice: LucideIcons.Dices,
  shuffle: LucideIcons.Shuffle,
  megaphone: LucideIcons.Megaphone,
  circleSlash: LucideIcons.CircleSlash,
  briefcase: LucideIcons.Briefcase,
  appWindow: LucideIcons.AppWindow,
  tablet: LucideIcons.Tablet,
  monitor: LucideIcons.Monitor,
  rotateCcw: LucideIcons.RotateCcw,
  undo: LucideIcons.RotateCcw,
  lifeBuoy: LucideIcons.LifeBuoy,
  video: LucideIcons.Video,
  minus: LucideIcons.Minus,
  mapPin: LucideIcons.MapPin,
  camera: LucideIcons.Camera,
  laptop: LucideIcons.Laptop,
  scale: LucideIcons.Scale,
  database: LucideIcons.Database,
  cloud: LucideIcons.Cloud,
  accessibility: LucideIcons.Accessibility,
  radio: LucideIcons.Radio,
  flaskConical: LucideIcons.FlaskConical,
  testTube: LucideIcons.TestTube,
  play: LucideIcons.Play,
  pause: LucideIcons.Pause,
  circle: LucideIcons.Circle,
  xCircle: LucideIcons.XCircle,
  bookOpen: LucideIcons.BookOpen,
  folder: LucideIcons.Folder,
  scroll: LucideIcons.Scroll,
  bot: LucideIcons.Bot,
  syringe: LucideIcons.Syringe,
  hourglass: LucideIcons.Hourglass,
  skull: LucideIcons.Skull,
  landmark: LucideIcons.Landmark,
  searchCheck: LucideIcons.SearchCheck,
  loader2: LucideIcons.Loader2,
  scanSearch: LucideIcons.ScanSearch,
};

/**
 * Categorias de ícones para exibição no Design System
 */
export const PROJECT_ICON_CATALOG = [
  {
    category: 'Agenda & Horários',
    description: 'Calendário, turnos (manhã, tarde, noite), agendamentos, intervalos e pausas de atendimento',
    icons: [
      { name: 'Calendar', key: 'calendar', label: 'Agenda / Calendário', tags: ['agenda', 'data', 'calendario'] },
      { name: 'Clock', key: 'clock', label: 'Horário / Tempo de Cadeira', tags: ['tempo', 'duracao', 'hora'] },
      { name: 'Sunrise', key: 'sunrise', label: 'Manhã / Abertura (08h-12h)', tags: ['manha', 'turno', 'cedo', 'abertura'] },
      { name: 'Sun', key: 'sun', label: 'Tarde / Vespertino (12h-18h)', tags: ['tarde', 'sol', 'turno'] },
      { name: 'Moon', key: 'moon', label: 'Noite / Noturno (18h+)', tags: ['noite', 'lua', 'turno', 'fechamento'] },
      { name: 'Coffee', key: 'coffee', label: 'Pausa / Intervalo do Barbeiro', tags: ['cafe', 'pausa', 'intervalo', 'descanso'] },
      { name: 'Briefcase', key: 'briefcase', label: 'Carga Horária / Escala', tags: ['trabalho', 'escala', 'expediente', 'carga'] },
      { name: 'Receipt', key: 'receipt', label: 'Comanda / Fechamento de Caixa', tags: ['comanda', 'recibo', 'caixa', 'pagamento'] },
      { name: 'FileText', key: 'fileText', label: 'Observações do Agendamento', tags: ['notas', 'observacoes', 'ficha', 'cliente'] },
      { name: 'AlertTriangle', key: 'alert', label: 'Aviso de Data Retroativa', tags: ['alerta', 'bloqueio', 'historico', 'warning'] },
      { name: 'Plus', key: 'plus', label: 'Novo Agendamento / Adicionar', tags: ['novo', 'agendar', 'adicionar', 'cadastrar'] },
    ]
  },
  {
    category: 'Barbearia & Atendimento',
    description: 'Serviços, barbeiros, cortes, agendamentos e atendimento ao cliente',
    icons: [
      { name: 'Scissors', key: 'scissors', label: 'Corte / Tesoura', tags: ['cabelo', 'barbearia', 'servico'] },
      { name: 'UserCheck', key: 'barber', label: 'Barbeiro / Profissional', tags: ['profissional', 'atendente'] },
      { name: 'Armchair', key: 'armchair', label: 'Cadeira de Barbeiro', tags: ['cadeira', 'atendimento', 'posto'] },
      { name: 'Building2', key: 'building2', label: 'Estabelecimento / Empresa', tags: ['barbearia', 'empresa', 'salao'] },
      { name: 'User', key: 'user', label: 'Cliente Individual', tags: ['perfil', 'usuario'] },
      { name: 'Users', key: 'users', label: 'Fila / Equipe', tags: ['clientes', 'barbeiros', 'time'] },
      { name: 'Dices', key: 'dices', label: 'Qualquer Barbeiro / Encaixe Rápido', tags: ['qualquer', 'aleatorio', 'dado', 'sem espera'] },
      { name: 'Megaphone', key: 'megaphone', label: 'Chamar no Painel / Fila', tags: ['painel', 'chamar', 'senha', 'aviso', 'recepcao'] },
      { name: 'Star', key: 'star', label: 'Avaliação / VIP', tags: ['estrelas', 'feedback', 'nota', 'vip'] },
      { name: 'Sparkles', key: 'sparkles', label: 'Especial / Premium', tags: ['destaque', 'vip', 'novidade'] },
      { name: 'Store', key: 'store', label: 'Unidade / Barbearia', tags: ['loja', 'filial', 'salao'] },
      { name: 'MapPin', key: 'mapPin', label: 'Localização / Endereço', tags: ['localizacao', 'endereco', 'mapa', 'cep', 'rua'] },
      { name: 'Camera', key: 'camera', label: 'Foto de Perfil / Avatar', tags: ['camera', 'foto', 'avatar', 'imagem'] },
      { name: 'Beer', key: 'beer', label: 'Bar / Cortesia', tags: ['bebida', 'cerveja', 'espera'] },
      { name: 'Wine', key: 'wine', label: 'Lounge / Bar', tags: ['drink', 'cortesia'] },
    ]
  },
  {
    category: 'Finanças & PDV',
    description: 'Caixa, pagamentos, comandas, produtos e relatórios de faturamento',
    icons: [
      { name: 'DollarSign', key: 'dollar', label: 'Faturamento / Real (R$)', tags: ['dinheiro', 'preco', 'lucro'] },
      { name: 'Wallet', key: 'wallet', label: 'Carteira / Saldo', tags: ['saldo', 'comissao', 'pagamento'] },
      { name: 'CreditCard', key: 'creditCard', label: 'Cartão / Maquininha', tags: ['credito', 'debito', 'pos'] },
      { name: 'Receipt', key: 'receipt', label: 'Comanda / Recibo', tags: ['cupom', 'consumo', 'fiscal'] },
      { name: 'Ticket', key: 'ticket', label: 'Fila / Senha / Ticket', tags: ['fila', 'senha', 'walk-in'] },
      { name: 'Percent', key: 'percent', label: 'Comissão / Desconto', tags: ['taxa', 'porcentagem', 'desconto'] },
      { name: 'Package', key: 'product', label: 'Produto / Estoque', tags: ['pomada', 'oleo', 'shampoo', 'item'] },
      { name: 'Tag', key: 'tag', label: 'Categoria / Etiqueta', tags: ['tag', 'promocao', 'categoria'] },
      { name: 'ShoppingBag', key: 'shoppingBag', label: 'Carrinho / PDV', tags: ['venda', 'compra', 'balcao'] },
      { name: 'BarChart3', key: 'barChart', label: 'Métricas / Relatório', tags: ['grafico', 'faturamento', 'indicadores'] },
      { name: 'TrendingUp', key: 'trendingUp', label: 'Crescimento', tags: ['alta', 'meta', 'lucro'] },
      { name: 'TrendingDown', key: 'trendingDown', label: 'Redução', tags: ['baixa', 'despesa', 'cancelamento'] },
    ]
  },
  {
    category: 'Navegação & Interface',
    description: 'Menus, abas, paginação, filtros, busca e seletores da interface',
    icons: [
      { name: 'LayoutDashboard', key: 'dashboard', label: 'Painel / Dashboard', tags: ['visao geral', 'home', 'painel'] },
      { name: 'Home', key: 'home', label: 'Início', tags: ['principal', 'raiz'] },
      { name: 'Search', key: 'search', label: 'Buscar / Filtrar', tags: ['pesquisa', 'localizar', 'filtro'] },
      { name: 'Filter', key: 'filter', label: 'Filtros Avançados', tags: ['refinar', 'ordem'] },
      { name: 'Sliders', key: 'sliders', label: 'Parâmetros / Ajustes', tags: ['configuracao', 'ajustes'] },
      { name: 'Layers', key: 'layers', label: 'Módulos / Camadas', tags: ['sistema', 'telas'] },
      { name: 'Palette', key: 'palette', label: 'Design System / Temas', tags: ['cores', 'marca', 'ambar'] },
      { name: 'Menu', key: 'menu', label: 'Menu Lateral / Gaveta', tags: ['sidebar', 'navegacao'] },
      { name: 'ChevronRight', key: 'chevronRight', label: 'Avançar / Próximo', tags: ['seta', 'paginacao'] },
      { name: 'ChevronDown', key: 'chevronDown', label: 'Expandir / Dropdown', tags: ['abrir', 'recolher'] },
      { name: 'ArrowRight', key: 'arrowRight', label: 'Continuar / Ir para', tags: ['link', 'fluxo'] },
      { name: 'ArrowLeft', key: 'arrowLeft', label: 'Voltar / Anterior', tags: ['voltar', 'retornar'] },
      { name: 'ArrowUpDown', key: 'arrowUpDown', label: 'Ordenar Coluna', tags: ['ordem', 'tabela'] },
      { name: 'Eye', key: 'eye', label: 'Visualizar / Ver Detalhes', tags: ['ver mais', 'detalhe'] },
      { name: 'EyeOff', key: 'eyeOff', label: 'Ocultar Senha', tags: ['senha', 'oculto'] },
      { name: 'Tablet', key: 'tablet', label: 'Tablet / Responsivo (768px)', tags: ['tablet', 'ipad', 'responsivo', 'viewport'] },
      { name: 'Monitor', key: 'monitor', label: 'Desktop / Tela Cheia (100%)', tags: ['desktop', 'tela', 'computador', 'monitor'] },
      { name: 'AppWindow', key: 'appWindow', label: 'Janela Modal / Diálogo', tags: ['modal', 'janela', 'dialog', 'popup'] },
    ]
  },
  {
    category: 'Ações & Ferramentas',
    description: 'Adicionar, editar, excluir, salvar, copiar e exportar arquivos',
    icons: [
      { name: 'Plus', key: 'plus', label: 'Adicionar / Novo', tags: ['cadastrar', 'incluir', 'criar'] },
      { name: 'Edit3', key: 'edit', label: 'Editar / Modificar', tags: ['alterar', 'atualizar'] },
      { name: 'Trash2', key: 'trash', label: 'Excluir / Desativar', tags: ['remover', 'apagar', 'lixeira'] },
      { name: 'Save', key: 'save', label: 'Salvar Alterações', tags: ['gravar', 'persistir'] },
      { name: 'Check', key: 'check', label: 'Confirmar / Sucesso', tags: ['concluir', 'aprovado'] },
      { name: 'CheckCircle2', key: 'checkCircle', label: 'Validado / Concluído', tags: ['sucesso', 'ok'] },
      { name: 'X', key: 'close', label: 'Fechar / Cancelar', tags: ['fechar', 'cancelar', 'rejeitar'] },
      { name: 'RotateCcw', key: 'rotateCcw', label: 'Reativar / Desfazer', tags: ['reativar', 'restaurar', 'desfazer'] },
      { name: 'Copy', key: 'copy', label: 'Copiar para Clipboard', tags: ['copiar', 'duplicar'] },
      { name: 'Download', key: 'download', label: 'Baixar / Exportar (PDF, JSON)', tags: ['exportar', 'download'] },
      { name: 'Upload', key: 'upload', label: 'Importar / Upload', tags: ['enviar', 'upload'] },
      { name: 'RefreshCw', key: 'refresh', label: 'Sincronizar / Atualizar', tags: ['recarregar', 'sync'] },
      { name: 'ExternalLink', key: 'externalLink', label: 'Link Externo', tags: ['abrir', 'externo'] },
      { name: 'Send', key: 'send', label: 'Enviar Notificação', tags: ['whatsapp', 'mensagem'] },
      { name: 'Settings', key: 'settings', label: 'Configurações', tags: ['preferencias', 'ajustes'] },
    ]
  },
  {
    category: 'Segurança, QA & DevSecOps',
    description: 'Autenticação, blindagem XSS, logs, testes de regressão e infraestrutura',
    icons: [
      { name: 'Shield', key: 'shield', label: 'Segurança / Blindagem', tags: ['protecao', 'appsec'] },
      { name: 'ShieldCheck', key: 'shieldCheck', label: 'Sanitizado / Auditado', tags: ['dompurify', 'aprovado'] },
      { name: 'Lock', key: 'lock', label: 'Bloqueado / Privado', tags: ['auth', 'senha', 'cripto'] },
      { name: 'Unlock', key: 'unlock', label: 'Desbloqueado', tags: ['acesso', 'liberado'] },
      { name: 'Key', key: 'key', label: 'Chave API / Credencial', tags: ['token', 'api key', 'jwt'] },
      { name: 'Terminal', key: 'terminal', label: 'Console de Logs & Correções', tags: ['terminal', 'bash', 'cli'] },
      { name: 'FileText', key: 'fileText', label: 'Documentação Técnica / Prontuário', tags: ['docs', 'arquitetura', 'manual', 'prontuario'] },
      { name: 'ClipboardList', key: 'clipboardList', label: 'Comandas / Ficha Técnica', tags: ['comandas', 'checklist', 'ordem'] },
      { name: 'FlaskConical', key: 'flask', label: 'Laboratório de Testes QA', tags: ['vitest', 'fuzzing', 'unit'] },
      { name: 'Zap', key: 'zap', label: 'Alta Performance / Atomicidade', tags: ['concorrencia', 'rapido'] },
      { name: 'Server', key: 'server', label: 'Servidor / Supabase DB', tags: ['banco', 'infraestrutura', 'backend'] },
      { name: 'Laptop', key: 'laptop', label: 'Sessão Desktop / Computador', tags: ['computador', 'desktop', 'sessao', 'login', 'dispositivo'] },
      { name: 'Network', key: 'network', label: 'Rede / Egress Seguro', tags: ['api', 'ssrf', 'webhook'] },
      { name: 'Bug', key: 'bug', label: 'Vulnerabilidade / Correção', tags: ['bug', 'patch', 'remediacao'] },
      { name: 'AlertTriangle', key: 'alert', label: 'Atenção / Advertência', tags: ['alerta', 'warning'] },
      { name: 'AlertCircle', key: 'alertCircle', label: 'Erro Crítico / Falha', tags: ['erro', 'danger'] },
      { name: 'ShieldAlert', key: 'shieldAlert', label: 'Alerta de Acesso / HTTP 403', tags: ['proibido', 'bloqueio', 'rbac'] },
      { name: 'CircleSlash', key: 'circleSlash', label: 'Não Cumpre / Reprovado', tags: ['reprovado', 'invalido', 'aaa'] },
      { name: 'Info', key: 'info', label: 'Informação Técnica', tags: ['ajuda', 'dica', 'guia'] },
    ]
  },
  {
    category: 'Fidelidade & Engajamento',
    description: 'Clube VIP, cupons, gamificação, programas de indicação e recompensas',
    icons: [
      { name: 'Crown', key: 'crown', label: 'Membro VIP / SuperAdmin', tags: ['premium', 'gold', 'vip'] },
      { name: 'Award', key: 'award', label: 'Recompensa / Conquista', tags: ['premio', 'pontos', 'medalha'] },
      { name: 'Gift', key: 'gift', label: 'Cupom / Presente', tags: ['desconto', 'fidelidade', 'brinde'] },
      { name: 'Flame', key: 'flame', label: 'Frequência / Em Alta', tags: ['fogo', 'pontualidade', 'sequencia'] },
      { name: 'Target', key: 'target', label: 'Metas da Equipe', tags: ['objetivo', 'desempenho'] },
      { name: 'Bell', key: 'bell', label: 'Lembrete / Notificações', tags: ['aviso', 'push', 'alerta'] },
      { name: 'Phone', key: 'phone', label: 'Telefone de Contato', tags: ['ligar', 'suporte'] },
      { name: 'Smartphone', key: 'smartphone', label: 'App / WhatsApp Webhook', tags: ['mobile', 'zap'] },
      { name: 'MessageSquare', key: 'message', label: 'Mensagens & Feedback', tags: ['conversa', 'chat', 'sac'] },
      { name: 'Rocket', key: 'rocket', label: 'Lançamento / Escala', tags: ['onboarding', 'crescimento'] },
    ]
  },
  {
    category: 'Suporte & Central de Ajuda',
    description: 'Help desk, chamados técnicos, plantão de emergência, WhatsApp e vídeos tutoriais',
    icons: [
      { name: 'LifeBuoy', key: 'lifeBuoy', label: 'Central de Ajuda / Suporte', tags: ['ajuda', 'suporte', 'socorro', 'helpdesk'] },
      { name: 'MessageSquare', key: 'messageSquare', label: 'Chamar Suporte no WhatsApp', tags: ['whatsapp', 'chat', 'conversa'] },
      { name: 'Video', key: 'video', label: 'Vídeos Tutoriais Rápidos', tags: ['tutorial', 'video', 'youtube', 'aulas'] },
      { name: 'AlertCircle', key: 'alertCircle', label: 'Plantão de Emergência / Crítico', tags: ['emergencia', 'critico', 'plantao'] },
      { name: 'Lightbulb', key: 'lightbulb', label: 'FAQ / Perguntas Frequentes', tags: ['faq', 'autoatendimento', 'ideia'] },
      { name: 'FileText', key: 'fileText', label: 'Abrir Chamado Interno / Ticket', tags: ['chamado', 'ticket', 'formulario'] },
      { name: 'ShieldCheck', key: 'shieldCheck', label: 'Suporte Blindado (Zero-XSS)', tags: ['seguranca', 'protecao', 'safehtml'] },
      { name: 'ExternalLink', key: 'externalLink', label: 'Assistir Tutoriais Externos', tags: ['link', 'externo', 'youtube'] },
    ]
  },
  {
    category: 'Engenharia de Qualidade, Squads & Infra',
    description: 'Ícones das squads técnicas (AppSec, DBA, SRE, Core APIs, UI/UX, Compliance) e painel de testes reais',
    icons: [
      { name: 'Shield', key: 'shield', label: 'Cyber Security & AppSec', tags: ['seguranca', 'appsec', 'squad', 'owasp', 'protecao'] },
      { name: 'Palette', key: 'palette', label: 'Front-End & UI/UX', tags: ['design', 'frontend', 'interface', 'squad', 'estilo'] },
      { name: 'Settings', key: 'settings', label: 'Back-End & Core APIs', tags: ['backend', 'api', 'config', 'squad', 'engrenagem'] },
      { name: 'Scale', key: 'scale', label: 'Compliance, DPO & LGPD', tags: ['compliance', 'dpo', 'lgpd', 'juridico', 'squad', 'balanca'] },
      { name: 'Database', key: 'database', label: 'Data Engineering & DBA', tags: ['dados', 'banco', 'dba', 'sql', 'squad', 'armazenamento'] },
      { name: 'Cloud', key: 'cloud', label: 'DevOps, SRE & Cloud Infra', tags: ['nuvem', 'cloud', 'sre', 'devops', 'squad', 'infra'] },
      { name: 'Rocket', key: 'rocket', label: 'Deploy & CI/CD Pipeline', tags: ['deploy', 'ci', 'cd', 'entrega', 'release', 'foguete'] },
      { name: 'Accessibility', key: 'accessibility', label: 'Acessibilidade WCAG (A11y)', tags: ['acessibilidade', 'wcag', 'a11y', 'inclusao'] },
      { name: 'Target', key: 'target', label: 'Métricas, QA & Metas', tags: ['metas', 'qualidade', 'sla', 'target', 'alvo'] },
      { name: 'Radio', key: 'radio', label: 'Telemetria & Comunicação Realtime', tags: ['telemetria', 'radio', 'websocket', 'realtime', 'antena'] },
      { name: 'Zap', key: 'zap', label: 'Performance & Alta Disponibilidade', tags: ['velocidade', 'performance', 'resiliencia', 'fast', 'raio'] },
      { name: 'FlaskConical', key: 'flaskConical', label: 'Testes Automatizados & QA Studio', tags: ['teste', 'vitest', 'qa', 'laboratorio', 'suite'] },
      { name: 'Play', key: 'play', label: 'Executar Suíte / Iniciar', tags: ['executar', 'play', 'rodar', 'iniciar', 'suite'] },
      { name: 'CheckCircle2', key: 'checkCircle2', label: 'Aprovado / Sucesso (100% OK)', tags: ['passou', 'aprovado', 'sucesso', 'ok', 'verde'] },
      { name: 'AlertCircle', key: 'alertCircle', label: 'Reprovado / Falha Crítica', tags: ['falha', 'reprovado', 'erro', 'danger', 'vermelho'] },
      { name: 'Circle', key: 'circle', label: 'Pendente / Aguardando Execução', tags: ['pendente', 'aguardando', 'cinza', 'fila'] },
      { name: 'BookOpen', key: 'bookOpen', label: 'Documentação Técnica / AppSec', tags: ['docs', 'manual', 'livro', 'appsec', 'estudo'] },
      { name: 'Folder', key: 'folder', label: 'Varredura de Arquivos / Pastas', tags: ['pasta', 'arquivo', 'diretorio', 'scan'] },
      { name: 'Scroll', key: 'scroll', label: 'Console de Logs & Telemetria', tags: ['logs', 'terminal', 'telemetria', 'pergaminho'] },
      { name: 'Bot', key: 'bot', label: 'Prompts de IA & Soluções', tags: ['ia', 'prompt', 'robo', 'automacao', 'solucao'] },
      { name: 'Wrench', key: 'wrench', label: 'Playbooks de Remediação & Ajuste', tags: ['remediacao', 'playbook', 'conserto', 'correcao'] },
      { name: 'Syringe', key: 'syringe', label: 'Injeção SQL / Fuzzing Pentest', tags: ['sqli', 'dangelo', 'injecao', 'pentest', 'fuzzing'] },
      { name: 'Hourglass', key: 'hourglass', label: 'Tempo de Execução / Em Andamento', tags: ['tempo', 'ampulheta', 'andamento', 'progresso'] },
      { name: 'RotateCcw', key: 'rotateCcw', label: 'Restauração de Estado Real / Reset', tags: ['reset', 'restaurar', 'reverter', 'rollback'] },
      { name: 'SearchCheck', key: 'searchCheck', label: 'Verificar se Foi Solucionado (Sonda)', tags: ['verificar', 'solucionado', 'sonda', 'auditoria', 'checagem'] },
      { name: 'Loader2', key: 'loader2', label: 'Spinner de Carregamento UX (Verificando)', tags: ['spinner', 'loading', 'carregando', 'verificando', 'progresso'] },
      { name: 'ArrowRight', key: 'arrowRight', label: 'Ver Detalhes / Próximo Passo', tags: ['seta', 'proximo', 'detalhes', 'acao'] },
    ]
  },
  {
    category: 'Mercado Pago API & Pagamentos',
    description: 'Gateway oficial do SaaS, Pix instantâneo, Checkout Pro, credenciais Sandbox/Live e telemetria de webhooks',
    icons: [
      { name: 'CreditCard', key: 'creditCard', label: 'Checkout Pro & Cartões de Crédito', tags: ['mercadopago', 'cartao', 'credito', 'debito', 'gateway'] },
      { name: 'QrCode', key: 'qrCode', label: 'Pix Instantâneo (QR Code & Copia-e-Cola)', tags: ['pix', 'qrcode', 'instantaneo', 'bcb'] },
      { name: 'Activity', key: 'activity', label: 'Ping Conexão & Health Check Real', tags: ['ping', 'health', 'latencia', 'conexao', 'status'] },
      { name: 'Key', key: 'key', label: 'Chaves Públicas (Public Key) & Credenciais', tags: ['public_key', 'chave', 'app_usr', 'credencial'] },
      { name: 'Lock', key: 'lock', label: 'Token de Acesso Privado (Access Token)', tags: ['access_token', 'segredo', 'privado', 'autenticacao'] },
      { name: 'ShieldCheck', key: 'shieldCheck', label: 'Segredo HMAC Webhook (Signature Secret)', tags: ['hmac', 'sha256', 'assinatura', 'segredo', 'whsec'] },
      { name: 'Terminal', key: 'terminal', label: 'Console de Telemetria & Logs em Tempo Real', tags: ['terminal', 'logs', 'telemetria', 'console', 'http'] },
      { name: 'Globe', key: 'globe', label: 'URL Oficial de Webhook para Notificações', tags: ['webhook', 'url', 'notificacao', 'endpoint'] },
      { name: 'Zap', key: 'zap', label: 'Emissão de Cobrança Instantânea', tags: ['cobranca', 'emissao', 'pix', 'rapido'] },
      { name: 'CheckCircle2', key: 'checkCircle2', label: 'Retorno 200 OK / Pagamento Aprovado', tags: ['200', 'sucesso', 'aprovado', 'confirmado'] },
      { name: 'AlertTriangle', key: 'alertTriangle', label: 'Retorno 400 Bad Request / Chave Rejeitada', tags: ['400', 'bad_request', 'aviso', 'erro'] },
      { name: 'AlertCircle', key: 'alertCircle', label: 'Retorno 401 Unauthorized / Token Expirado', tags: ['401', 'unauthorized', 'rejeitado', 'falha'] },
      { name: 'FlaskConical', key: 'flaskConical', label: 'Ambiente de Testes (Sandbox)', tags: ['sandbox', 'teste', 'homologacao', 'simulacao'] },
      { name: 'Rocket', key: 'rocket', label: 'Ambiente de Produção (Live)', tags: ['producao', 'live', 'publicacao', 'real'] },
      { name: 'RotateCcw', key: 'rotateCcw', label: 'Resetar Console & Restaurar Segredo', tags: ['reset', 'restaurar', 'padrao', 'recarregar'] },
      { name: 'Save', key: 'save', label: 'Salvar Credenciais da API', tags: ['salvar', 'gravar', 'configurar', 'persistir'] },
    ]
  }
];

/**
 * ProjectIcon Component
 *
 * Herda a Paleta Oficial Âmbar Nobre do projeto por padrão.
 *
 * @param {string} name - Nome do ícone (PascalCase do Lucide, chave semântica em ICON_MAP ou emoji)
 * @param {number|string} size - Tamanho em pixels (padrão: 18)
 * @param {string} className - Classes Tailwind adicionais
 * @param {string} colorVariant - 'amber' (padrão - Âmbar Nobre), 'amber-dark', 'amber-light', 'gold', 'emerald', 'danger', 'info', 'neutral', 'white', 'inherit'
 * @param {number} strokeWidth - Espessura do traço (padrão: 2)
 */
export default function ProjectIcon({
  name,
  size = 18,
  className = '',
  colorVariant = 'amber',
  strokeWidth = 2,
  ...props
}) {
  // 1. Resolução se for emoji
  let resolvedName = name;
  if (typeof name === 'string' && EMOJI_TO_ICON_MAP[name]) {
    resolvedName = EMOJI_TO_ICON_MAP[name];
  }

  // 2. Localização do componente em ICON_MAP ou LucideIcons
  let IconComponent = null;

  if (typeof resolvedName === 'string') {
    if (ICON_MAP[resolvedName]) {
      IconComponent = ICON_MAP[resolvedName];
    } else if (LucideIcons[resolvedName]) {
      IconComponent = LucideIcons[resolvedName];
    } else {
      // Tenta capitalização PascalCase
      const pascal = resolvedName.charAt(0).toUpperCase() + resolvedName.slice(1);
      if (LucideIcons[pascal]) {
        IconComponent = LucideIcons[pascal];
      }
    }
  }

  if (!IconComponent) {
    IconComponent = LucideIcons.Sparkles;
  }

  // 3. Paleta de Cores Oficial: Âmbar Nobre (--brand-500: #f59e0b) e Tokens de Design
  const colorStyles = {
    amber: 'text-amber-500 dark:text-amber-400',
    'amber-nobre': 'text-amber-500 dark:text-amber-400',
    'amber-dark': 'text-amber-600 dark:text-amber-500',
    'amber-light': 'text-amber-400 dark:text-amber-300',
    gold: 'text-amber-300',
    brand: 'text-[var(--brand-500,#f59e0b)]',
    'brand-primary': 'text-[var(--brand-600,#d97706)]',
    emerald: 'text-emerald-500 dark:text-emerald-400',
    success: 'text-emerald-500 dark:text-emerald-400',
    danger: 'text-rose-500 dark:text-rose-400',
    ruby: 'text-rose-500 dark:text-rose-400',
    info: 'text-sky-500 dark:text-sky-400',
    sapphire: 'text-sky-500 dark:text-sky-400',
    neutral: 'text-neutral-400 dark:text-neutral-500',
    white: 'text-white',
    inherit: 'text-inherit',
  };

  // Se className já contém uma cor de texto explícita (ex: text-white, text-neutral-400, text-emerald-400)
  // e colorVariant não foi explicitamente modificado, respeitamos a classe passada
  const hasCustomTextColor = /\btext-(?!xs|sm|base|lg|xl|2xl|3xl|4xl|5xl|left|center|right|justify)/.test(className);
  const selectedColor = hasCustomTextColor && colorVariant === 'amber'
    ? ''
    : (colorStyles[colorVariant] || colorStyles.amber);

  return (
    <IconComponent
      size={size}
      strokeWidth={strokeWidth}
      className={`inline-block shrink-0 transition-colors ${selectedColor} ${className}`}
      aria-hidden="true"
      {...props}
    />
  );
}
